### ISSUE TITLE
Emergency pause of ZRC-20 contract

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1037]

**Comment by lumtis** [comment]
Does a solution for this have been already designed @zeta-chain/protocol-engineering ?
I think a solution can be:
- Adding a `paused` boolean in `ForeignCoin` structure
- In `PostTx` evm hook, verify if a paused zrc20 has been called, if yes revert the tx
- Implement message for updating paused value, we could have an array to pause several contract in the same message
