### ISSUE TITLE
Rename `ZetaMinted` in `MsgVoteOnObservedOutboundTx`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1070]
In `MsgVoteOnObservedOutboundTx` we have a field named `ZetaMinted` to check against the value that has been received on the other chain after the outbound is mined.

When `CoinType == Gas` this value represents the native chain token received. We should therefore rename the field into something like `ValueReceived`

**Comment by brewmaster012** [comment]
this is very much needed! The naming was historical and super confusing.
