### ISSUE TITLE
Upgrade libp2p to at least v0.27.8

### ISSUE THREAD

**Issue by greg-szabo** [zeta-chain/node#1074]
The current version of libp2p both in release [v8.3.3](https://github.com/zeta-chain/node/blob/3046a78693971efafaffb19ffdb5710356f77649/go.mod#L201) and on [develop](https://github.com/zeta-chain/node/blob/3046a78693971efafaffb19ffdb5710356f77649/go.mod#L201) (and in v9 too, although that's not published in the chain registry yet) is set to v0.22.0.

The libp2p library is developed in lockstep with the Go compiler version and it only supports the last two major Go versions. (See notes [here](https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions).)

As of August 8, Go 1.19 is end of life and unsupported. (See note [here](https://endoflife.date/go).)

Some risks this might pose:
* Any developers keeping their Go version up-to-date will run into an error when trying to build the source code. (Mitigated by the README stating Go 1.19 is required.)
* Any newly uncovered compiler bugs will not make it into Go 1.19, leaving binary builds vulnerable. (This is usually a risk about once every two to three years.)
* The libp2p v0.22 library is fairly old. Looking at v0.23 I didn't find immediate security fixes that have to be applied but in the year's worth of work, something might have come up, that's worth looking at. (Admittedly, this is low priority but someone should go through the changelogs.)
* The newer versions of Cosmos SDK will require Go 1.20 or above. (Also a low priority, until an upgrade.)

I understand that upgrading libp2p is not an easy undertaking, so I consider this a tracking issue (unless the team has some other ways of tracking it).

**Comment by brewmaster012** [comment]
@greg-szabo  Thanks for the helpful suggestion and the pointers!

I think minimum we should move to go 1.20. 
@lumtis you wanna take a stab at this? Not the highest priority right now but if it's relatively straightforward we should do it soon. cc @fadeev @kingpinXD @CharlieMc0
