### ISSUE TITLE
Developers need ability to fork Eth to LocalNet

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#108]
The ability to fork MainNet & public testnets will be very useful for developers. 

**Use Cases**
* Fork ETh to LocalNet so to use UniSwap liquify pools 
*  Test against real world smart contracts
* Eliminate the need to deploy contracts that already exist publically. 

Requested by @lucas-janon & @tarunyadav1

**Comment by lumtis** [comment]
Looks no longer relevant, please feel free to reopen otherwise
