### ISSUE TITLE
ZetaClient should support multiple end points for redundancy  

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#109]
ZetaClientd should support an optional secondary endpoint for each chain. This would allow ZetaClientd to fail over to its secondary endpoint if the first endpoint becomes unavailable. 

This will make it easier for nodes operators to ensure their node remains hyperconnected and makes the network more resilient.

**Comment by lumtis** [comment]
Looks still very relevant now?

**Comment by lumtis** [comment]
Closing as we discussed it can be implemented on top of the ZetaClient
