### ISSUE TITLE
bitcoin: support inbound/outbound legacy P2PKH address format

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#1124]
Currently, only SegWit native (P2WPKH address) inbound/outbound transactions are supported to/from the TSS address. 
Therefore the user must use a wallet with SegWit address (bc1xxxx) to call omni-chain smart contracts or deposit, and can only withdraw to such wallet address as well. 

This is limiting as legacy P2PKH address is still in wide use [glassdoor report](https://insights.glassnode.com/segwit-adoption/)

**Comment by lumtis** [comment]
Should we consider it for https://github.com/zeta-chain/node/issues/1035 @brewmaster012 ?

**Comment by brewmaster012** [comment]
Ideally yes, but it's not the highest priority.
