### ISSUE TITLE
Error after installing a node on the server

### ISSUE THREAD

**Issue by velyar** [zeta-chain/node#1173]
I install the node from the site https://app.nodejumper.io/zetachain-testnet/installation. Everything goes without errors, I restore my wallet, the command works, I look at the list of wallets, the command works. But I want to see the wallet balance and it gives an error. The node is synchronized, shows the latest blocks, logs without errors. The blocks were of course not completely downloaded, but using a snapshot. But this doesn't seem to be the reason. Anyone who has encountered this, I apologize in advance if I am in the wrong place, but no one else can help me figure this out)
![image](https://github.com/zeta-chain/node/assets/22917604/5a33a58c-9f2f-424b-8c3b-d77e0b47bff3)
![image](https://github.com/zeta-chain/node/assets/22917604/dd243262-c36a-4b38-9514-b1650cb7b11e)
![image](https://github.com/zeta-chain/node/assets/22917604/c353489f-e6cc-4bea-9ce2-f8f178624e9a)

**Comment by brewmaster012** [comment]
@velyar what version of zetacore are you using?

**Comment by brewmaster012** [comment]
it might be better to ask in the discord node channel. @velyar

**Comment by velyar** [comment]
As it became known in recent days, everyone has such a problem. But for now the problem is solved if you add this parameter.
`--node https://zetachain-athens.blockpi.network:443/rpc/v1/public -y`
So I guess I'll close this issue:)
