### ISSUE TITLE
Ask for Help: Benchmark local net of zeta-chain for multiple validators nodes and two evm local net

### ISSUE THREAD

**Issue by KunPengRen** [zeta-chain/node#1179]
Dear zeta-chain team,

I am working on testing the performance of the zeta-chain. To test the scalability of the network, it's better to run with multiple validators together. Here is one test config, like 32 zeta-chain validators node and two Ethereum local network (each has four nodes).

I observed in your local net test files, that only two validators nodes. May I ask how to add more nodes in the local net?
Can I just add in the docker-compose file?

If you can provide the docker-compose file for 32 validator nodes, it will help me a lot.

Note: this will be a part of my research paper, where I compare my research work with zeta-chain.

**Comment by KunPengRen** [comment]
@lumtis 
Thanks for your replay. I saw you have create a new issue about multiple zeta-chain validators local net. I will close this issue, and wait the update from your team

**Comment by lumtis** [comment]
> @lumtis Thanks for your replay. I saw you have create a new issue about multiple zeta-chain validators local net. I will close this issue, and wait the update from your team

This is a more general-purpose issue, we can look to have a quicker fix for this particular issue if the node number is the only blocker.

**Comment by KunPengRen** [comment]
@lumtis Currently, I am working on benchmarking the message passing in the two validator nodes network, I think my script also works for more nodes number

**Comment by lumtis** [comment]
> @lumtis Currently, I am working on benchmarking the message passing in the two validator nodes network, I think my script also works for more nodes number

Great, let us know if any help is needed.
