### ISSUE TITLE
Rename `ForeignCoins` into `ForeignCoin`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1182]
It seems to me that the name of the structure should be singular since it represents a single coin on a foreign chain.

**Comment by AirDoodle** [comment]
hi, @lumtis can I try this one?

**Comment by chixiaowen** [comment]
hi, @lumtis   can I try this?

**Comment by chixiaowen** [comment]
hello?

**Comment by lumtis** [comment]
Hi @chixiaowen , we are currently under heavy workload that's why we might take few days to respond.
Thanks for the contribution, I will look at it.

**Comment by lumtis** [comment]
Closing in favor of https://github.com/zeta-chain/node/issues/2993
