### ISSUE TITLE
[TRACKING] floating point arithmetic

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#120]
FP arithmetic is problematic since it's not re-producible and IEEE 754 compliant machine can generate (slightly) different answer. 

Should avoid FP arithmetic at the state machine level. 

Places that we still use FP arithmetic: 

- [ ] zetacore: calculating fees and convert in ZETA
- [ ] zetaclient: compute uniswap v3 time weighted average

**Comment by lumtis** [comment]
Looks no longer relevant, please feel free to reopen otherwise
