### ISSUE TITLE
CCTX not reverted while contract revert

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1212]
With contract https://zetachain-athens-3.blockscout.com/address/0x2AaFf535d013AfD6c70829E395eD0E20EC01Cd72

`OnCrosschainCall` always reverts 

But a CCTX is not reverted
https://[zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/crosschain/cctx/0xa1634a604861a42ab16c3a2d5d1bf3ffa021a29e8784659a9623a60d06bc602f](https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/crosschain/cctx/0xa1634a604861a42ab16c3a2d5d1bf3ffa021a29e8784659a9623a60d06bc602f)

There might be a bug in the tx result verification

cc @fadeev

**Comment by brewmaster012** [comment]
this is related to https://github.com/zeta-chain/node/issues/1216 right? 
In current logic this is expected, because a message that consists of nothing other than an address is a deposit, without contract call.

**Comment by lumtis** [comment]
>this is related to https://github.com/zeta-chain/node/issues/1216 right?
Yes, this was the source of the issue in the linked links.

>In current logic this is expected, because a message that consists of nothing other than an address is a deposit, without contract call.
This might be expected in the protocol logic but right now there is no information for the developer that if they implement a `OnCrossChainCall` function that doesn't utilize message content, it will not be called if there is a `DepositAndCall` without data and the deposited tokens will be lost.
The thing is that it is a very rare case where you deposit tokens to a smart contract without triggering some logic. Since you lose the context of the sender, a regular deposit into a contract is like a donation to it and if there is no function using these tokens it means that the deposited zrc20s are lost.
On the other side, it can be very usual to have a `OnCrossChainCall` using sender address, and amount but without using message content, like adding liquidity in a pool for example.
This is the reason why I think it would make more sense to always call `OnCrossChainCall` when the receiver is a contract. In case the developer want to allow simple deposit, the function can be implemented with an empty body.
This would be like the behavior with fallback functions for contract receiving Ether. If a fallback function, or receive function is not defined in the contract, depositing Ethers to it fails.
