### ISSUE TITLE
`keeper/gas_price.go`: loss of error context

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1213]
When the EVM call method fails, we return a new error and dismiss the returned error by evm.
https://github.com/zeta-chain/node/blob/007ff12dacf5142933bdce06ad2da724a992bd6e/x/fungible/keeper/gas_price.go#L28

We should keep the full context in the error.

**Comment by chinmaym07** [comment]
Hey @lumtis  Can I contribute to this ?
will it be better to separate the 2 errors ?

**Comment by lumtis** [comment]
> Hey @lumtis Can I contribute to this ? will it be better to separate the 2 errors ?

Sure, you can go ahead, thanks for your interest in contributing.

Yes, we could separate into 2 errors, one where we return the error itself, the other where we just say the tx failed

**Comment by lumtis** [comment]
Assigning it to you @chinmaym07, let me know if you need any other info or if you can't take it anymore
