### ISSUE TITLE
Allowing cross-chain call with empty messages

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1216]
## Problem

We currently make a ZRC20 deposit without a cross-chain call if the message only contains an address without data.
https://github.com/zeta-chain/node/blob/007ff12dacf5142933bdce06ad2da724a992bd6e/x/fungible/keeper/deposits.go#L52

This can result in loss of funds if sent to a contract and the contract doesn't have a way to recover it, it also lose the sender context since it only deposits the tokens.

## A solution

In
https://github.com/zeta-chain/node/blob/007ff12dacf5142933bdce06ad2da724a992bd6e/x/fungible/keeper/deposits.go#L51C5-L51C5
We should also verify that the address is a contract (checking `codeHash != ""` ?) if it is a contract, we should call `DepositZRC20AndCallContract` if it is an EOA we should call `DepositZRC20`

**Comment by brewmaster012** [comment]
hmm.. is this a bit too complicated though?

**Comment by lumtis** [comment]
>hmm.. is this a bit too complicated though?

I think checking if an account is a EOA or a contract can be simple.
