### ISSUE TITLE
Omnichain transaction not processed

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1217]
https://goerli.etherscan.io/tx/0x8804924ee2eff23b76f2ffb11e5aeb6d615911e4dec00c4c201d76a316863351

The TX includes an omnichain contract address (`0xf8027648a5D631e6D2C03B8D550Dd034230dB0be`) and some random data to ensure that the contract is called. The contract contains no logic (it's an empty template).

The TX is broadcasted from a script:

https://github.com/zeta-chain/toolkit/blob/cba6c7cc40ac428f6fe4125aef58ed29a3df407f/scripts/integration.sh#L44

**Comment by fadeev** [comment]
None of my TXs are processed 😬

https://mumbai.polygonscan.com/tx/0xbfdd6360cc2afd7090bf745011648e6024f056d3b6913df5748860a21a3fb43e

https://goerli.etherscan.io/tx/0xe973ffc41ae1f4755cf6f82413670d60a43ee535303f36feb8e06160ff426bb4

**Comment by lumtis** [comment]
Closing as the related incident has been resolved. Feel free to reopen if still encountering the issue
