### ISSUE TITLE
Ability to add trackers manually should be restricted to multi-sig admin group

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#1248]
Currently, trackers can be manually added by O/S operators and the admin group. This should be restricted to the admin group only because an attacker must compromise multiple signers to submit a false tracker. Under the current model a single operator being compromised could result in submission of false or malicious trackers.

`zetacored tx crosschain add-to-out-tx-tracker`

**Comment by kingpinXD** [comment]
Closing this in Favor of 
https://github.com/zeta-chain/node/issues/1318
