### ISSUE TITLE
Create specific `IsEthereumChain` function for chains using Ethereum block header format

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1272]
We currently use 
- `IsEVMChain`: chain using EVM for execution layer
- `IsEthereumChain`: Ethereum mainnet and testnets

We currently use one of these functions to determine if we should use the `EthereumProof` object for header and permissionless tx verification

However:
- There could be other chains than Ethereum mainnet and testnets that use the same header format therefore `IsEthereumChain` is not adapted
- Not all EVM chains use the Ethereum header format (ZetaChain itself), therefore `IsEVMChain` is not adapted

We need a specific function that determine if a chain can use the Ethereum header format for proof
@ws4charlie idea: `IsCompatibleWithEthHeader`

**Comment by kingpinXD** [comment]
This pr has a similar implementation 
https://github.com/zeta-chain/node/pull/1334/files#diff-19c25815bf12dd0469c0f1d7962931fb154fc029ebf203532448b0a6535335f1

**Comment by lumtis** [comment]
It looks like yes, although I would rename it from `IsHeaderSupportedEvmChain` to something like `IsEthereumHeader` as you could have EVM chain we could support in the future using a different header format.

**Comment by lumtis** [comment]
Completed
