### ISSUE TITLE
crosschain: Ignore funding the Gas Stability Pool when remaining fees are 0 

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/node#1287]
When GasLimit == GasUsed it should be returned directly.
https://github.com/zeta-chain/node/blob/db3e5072f6e94daba7f89974a838fb4a63422e3f/x/crosschain/keeper/keeper_cross_chain_tx_vote_outbound_tx.go#L231

**Comment by lumtis** [comment]
Good catch.
Feel free to make a PR if you want to work on this 👍

**Comment by lukema95** [comment]
> Good catch. Feel free to make a PR if you want to work on this 👍

Sure, I will make a PR later.
