### ISSUE TITLE
fungible: Wrong parameter when calling addLiquidityETH function.

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/node#1294]
1. According to the contract, the last parameter of `addLiquidityETH` should be a timestamp, but `amountAZeta` is used here, which seems to be incorrect.
https://github.com/zeta-chain/node/blob/fb82095fb4776620ca9e08c330adf88ec316d223/x/fungible/keeper/gas_coin_and_pool.go#L111

2. The fifth parameter of the `CallEVM` function should represent the amount of ZETA. However, `amount` here represents the quantity of the ZRC20 token. Therefore, it should be changed to `amountAZeta`.
https://github.com/zeta-chain/node/blob/fb82095fb4776620ca9e08c330adf88ec316d223/x/fungible/keeper/gas_coin_and_pool.go#L110

**Comment by brewmaster012** [comment]
@lukema95 thanks for the report! see my comment below

> 1. According to the contract, the last parameter of `addLiquidityETH` should be a timestamp, but `amountAZeta` is used here, which seems to be incorrect.
>    https://github.com/zeta-chain/node/blob/fb82095fb4776620ca9e08c330adf88ec316d223/x/fungible/keeper/gas_coin_and_pool.go#L111

Here the `amountAZeta` is basically used as a really large number that says "no deadline". 

> 2. The fifth parameter of the `CallEVM` function should represent the amount of ZETA. However, `amount` here represents the quantity of the ZRC20 token. Therefore, it should be changed to `amountAZeta`.
>    https://github.com/zeta-chain/node/blob/fb82095fb4776620ca9e08c330adf88ec316d223/x/fungible/keeper/gas_coin_and_pool.go#L110

yeah this is right. can you make a PR and fix that?

**Comment by lukema95** [comment]
> @lukema95 thanks for the report! see my comment below
> 
> > 1. According to the contract, the last parameter of `addLiquidityETH` should be a timestamp, but `amountAZeta` is used here, which seems to be incorrect.
> >    https://github.com/zeta-chain/node/blob/fb82095fb4776620ca9e08c330adf88ec316d223/x/fungible/keeper/gas_coin_and_pool.go#L111
> 
> Here the `amountAZeta` is basically used as a really large number that says "no deadline".
> 
> > 2. The fifth parameter of the `CallEVM` function should represent the amount of ZETA. However, `amount` here represents the quantity of the ZRC20 token. Therefore, it should be changed to `amountAZeta`.
> >    https://github.com/zeta-chain/node/blob/fb82095fb4776620ca9e08c330adf88ec316d223/x/fungible/keeper/gas_coin_and_pool.go#L110
> 
> yeah this is right. can you make a PR and fix that?

Sure, I will submit a PR later
