### ISSUE TITLE
BTC ZRC-20 name is very verbose

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1298]
Not a big deal, but it doesn't match other ZRC-20's names, so might be a bit confusing.

```js
    {
      "zrc20_contract_address": "0x65a45c57636f9BcCeD4fe193A602008578BcA90b",
      "asset": "",
      "foreign_chain_id": "18332",
      "decimals": 8,
      "name": "BTC-btc_testnet-btc_testnet", // <-- Not sure we need to be so verbose
      "symbol": "tBTC",
      "coin_type": "Gas",
      "gas_limit": "100",
      "paused": false
    },
```

<img width="1206" alt="Screenshot 2023-10-16 at 11 26 26" src="https://github.com/zeta-chain/node/assets/332151/0b8df64c-07a3-4bc9-be67-aafef7c2ebfa">

Source: https://zetachain-athens.blockpi.network/lcd/v1/public/zeta-chain/zetacore/fungible/foreign_coins

**Comment by lumtis** [comment]
We'll be part of operation to rename all ZRC20s
