### ISSUE TITLE
encode more than 80 bytes in incoming BTC transaction

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#1305]
Currently any inbound bitcoin transaction must provide an output often termed "MEMO" that includes [20B contract address] + [arbitrary length message] that remotely calls smart contract on zEVM. 

However as Bitcoin network does not typically allow more than 80Bytes in the memo field (OP_RETURN, SIZE, DATA], it could be limiting the size of the message in the remote contract call from Bitcoin network. 

Investigate reliable ways to encode more bytes into a bitcoin transaction.

**Comment by lumtis** [comment]
Completed
