### ISSUE TITLE
`zetacore` : Limit tracker creation proof based trackers only 

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#1318]
Limit tracker creation to proof-based trackers only and remove any type of permission such as Admin or Observer

**Comment by lumtis** [comment]
Don't we want to keep permissions for admin group 2?
Also don't we want to keep it for chains for proof system can't be implemented or won't be directly implemented?

**Comment by kingpinXD** [comment]
Yes .Moved this to the backlog for now. I will be working of adding proof based trackers first and then phase permissions out .
Will try to paste my plan from the slack thread into the comments here

**Comment by kingpinXD** [comment]
https://zetachain.slack.com/archives/C04GM8RV5E3/p1697593937717429?thread_ts=1697219384.292809&cid=C04GM8RV5E3

**Comment by lumtis** [comment]
No longer relevant for the time being
