### ISSUE TITLE
crosschain: Gas needs to be returned after the transaction fails

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/node#1324]
I'm a bit confused about the logic in this line of code. If there are no errors here and Gas has been deducted correctly, shouldn't the remaining Gas be refunded to the user?
https://github.com/zeta-chain/node/blob/036b13277086378fe2927e7808fba6e96e87cf0c/x/crosschain/keeper/keeper_cross_chain_tx_vote_inbound_tx.go#L186

**Comment by lumtis** [comment]
Hi @lukema95 what do you mean by `If there are no error here`?
The quoted line actually checks if there is an error, if there is no error the revert tx and created with the remaining amount, deducted from the gas payment.

**Comment by lukema95** [comment]
> Hi @lukema95 what do you mean by `If there are no error here`? The quoted line actually checks if there is an error, if there is no error the revert tx and created with the remaining amount, deducted from the gas payment.

What I mean is, if `err == nil`, shouldn't we call `RefundAmountOnZetaChain` to return the remaining amount to the user?

**Comment by lumtis** [comment]
> > Hi @lukema95 what do you mean by `If there are no error here`? The quoted line actually checks if there is an error, if there is no error the revert tx and created with the remaining amount, deducted from the gas payment.
> 
> What I mean is, if `err == nil`, shouldn't we call `RefundAmountOnZetaChain` to return the remaining amount to the user?

If `err == nil` then a revert tx is created with the remaining amount of the crosschain transactions. The revert tx will refund the user on the source chain.

**Comment by lukema95** [comment]
> > > Hi @lukema95 what do you mean by `If there are no error here`? The quoted line actually checks if there is an error, if there is no error the revert tx and created with the remaining amount, deducted from the gas payment.
> > 
> > 
> > What I mean is, if `err == nil`, shouldn't we call `RefundAmountOnZetaChain` to return the remaining amount to the user?
> 
> If `err == nil` then a revert tx is created with the remaining amount of the crosschain transactions. The revert tx will refund the user on the source chain.

I got it.👍
