### ISSUE TITLE
`zetaclient` : submit proof based inbound trackers 

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#1333]
Add a new thread to zetaclient 
It should 
 - Scan inbound TXS (connector , erc20custody, and TSS address ) on all EVM chains , TSS address only on BTC chain 
 - If the tx is past confirmation blocks ,check if a ballot has been created 
 - If the ballot is not created , add a inbound tracker with proof , which suggests the clients to verify the tx and vote fo it if in case they missed voting

**Comment by lumtis** [comment]
No longer relevant for the time being
