### ISSUE TITLE
backlog: bitcoin utxo consolidation fee

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1337]
We now have the utxo consolidation logic when assembling each bitcoin outTx, but consolidation will cost extra gas fee as the transaction size increases. It's okay for Zetachain to pay the extra fee in short term. As traffic grows, the utxo consolidation might become a non-negligible cost.  Charging a `utxo consolidation fee` from users who send utxo to TSS address could be a potential solution.

**Comment by lumtis** [comment]
Does the `utxo consolidation fee` increase linearly along the tx size? Because in this case maybe the solution could be to set a higher gas price.

**Comment by ws4charlie** [comment]
The [PR](https://github.com/zeta-chain/node-private/pull/50) got merged in develop branch of node.
