### ISSUE TITLE
zetaclient: Remove redundant sorting of trackers.

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/node#1342]
The operation of sorting the `trackers` below is redundant. 
https://github.com/zeta-chain/node/blob/9028fe3e5ba17d01d7cb58e23594d7e559718278/zetaclient/evm_client.go#L561

In the preceding function `GetAllOutTxTrackerByChain`, we have already sorted the `trackers`.
https://github.com/zeta-chain/node/blob/9028fe3e5ba17d01d7cb58e23594d7e559718278/zetaclient/evm_client.go#L557

**Comment by lumtis** [comment]
Hey @lukema95, this looks a relevant issue to me, thanks for noticing 👍
Feel free to work on it if you want.

**Comment by lukema95** [comment]
> Hey @lukema95, this looks a relevant issue to me, thanks for noticing 👍 Feel free to work on it if you want.

Sure, you can assign it to me.
