### ISSUE TITLE
`observer` : refactor Add observer 

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#1349]
Add observer TX can be broken down into
 - Add Node Account 
 - Add Observer

**Comment by lumtis** [comment]
We already the boolean `AddNodeAccountOnly` in `MsgAddObserver`, can't it be already used for this?

**Comment by kingpinXD** [comment]
Closing this task, as `Add Node Account` cannot be reused for Update Observer.
We should only update the operator's address. 

Updating the hotkey will cause issues with signing outbound tx's as the TSS server uses the hotkey publickey to generate the peer id stored in the address book.
