### ISSUE TITLE
List and implement missing CLI commands for messages

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1356]
Msg CLI commands are useful for testing and experimentation.

Some messages don't have a CLI command implemented. We should implement it for all messages.

**Comment by lukema95** [comment]
Maybe I can do something about this.

**Comment by lumtis** [comment]
For sure if you're interested. The idea is to have a basic CLI command for every message with every fields as an argument.

**Comment by lumtis** [comment]
Let's only create remaining ones when needed
