### ISSUE TITLE
Get the list of chains from configuration

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/node#1361]
Currently `GetChainFromChainID` uses the `DefaultChainsList` function to get the list of chains, which is hard-coded. Should we read the list of chains from the configuration? This makes it more flexible and configurable.
https://github.com/zeta-chain/node/blob/6567637545769a01a8406fd8fc9ad4427b7cb725/common/chain.go#L189

**Comment by lumtis** [comment]
We plan to remove the different build types: https://github.com/zeta-chain/node/issues/1331

I think this task will be part of it since we will no longer be able to directly use hardcoded values.

**Comment by lumtis** [comment]
Closing as we can now get the supported chains for the `observer` module through the chain params
