### ISSUE TITLE
Misprint in 2 test cases

### ISSUE THREAD

**Issue by adust09** [zeta-chain/node#1389]
I found 2 minimum misprint.
It's should be bob instead. 
`	// alice is the default user created by Starport chain serve
`
1. https://github.com/zeta-chain/node/blob/develop/zetaclient/voter_test.go#L62
2. https://github.com/zeta-chain/node/blob/develop/zetaclient/zetacore_observer_test.go#L71

**Comment by lumtis** [comment]
Yeah we should actually remove these comments since we no longer use Starport/Ignite
