### ISSUE TITLE
Zetaclients have divided opinions on confirmed outTx's block height and gas used

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1392]
Example outTx (119092): https://goerli.etherscan.io/tx/0xfd5874bf532473b04be98c3936f24af38ad45e30b4ef98783f59e43d1cbc0bec

The impact: the cctx and tracker became pending-forever.
How to recover: restart those zetaclients who had false opinion and let the cast votes once again.

============opinion 1 (true)
ballot1: https://explorer.zetachain.com/cosmos/tx/3720C3D31EE517122D5B5A5151587A5E4A3371F40CABBD210E37D81C5AFCE038
ballot2: https://explorer.zetachain.com/cosmos/tx/8A8C878D719A5EC6C6FD1FECF3C04BCF03E2D9D1B5753DE8263014888C4BA844
ballot3: https://explorer.zetachain.com/cosmos/tx/BC80C8E38948A9C36547DB867AB7616BCAC4614B5283F47C13B802981E20BDDA
ballot4: https://explorer.zetachain.com/cosmos/tx/A13DBD236060F969E6AD8DCCDD92222204478C2239CBA76CA768C909D4B1A1DC

============opinion 2 (false)
ballot5: https://explorer.zetachain.com/cosmos/tx/59852E79993BB3E89C5B41EB818B8D7753C546C74EC1734842DA46CEB84D5803
ballot6: https://explorer.zetachain.com/cosmos/tx/5C95FDCE22414DBB2B4D27FB6CC0BE6AAB2995B50F3251AC34EE7FE94584F8F2
ballot7: https://explorer.zetachain.com/cosmos/tx/2DFFF0634EB09F848C7CB66AF43A0494E0CEA7894BAD4C931280E1FFA15CB82F
ballot8: https://explorer.zetachain.com/cosmos/tx/40661A2D9F0BC8145EBB46910BBCD8175EB9579976FFBC78D4980CE54A0A399A

![image](https://github.com/zeta-chain/node/assets/34498985/811a8d8b-efd8-4bb8-937d-6dd4012daa76)

**Comment by lumtis** [comment]
What is the underlying issue for ZetaClient voting with a wrong value?

**Comment by ws4charlie** [comment]
I don't know the reason yet. It needs some investigation. Another recent example

outTx (119826): https://goerli.etherscan.io/tx/0x391bef29c2f6325b96db6c6a1dc42df2aa707eb61b9b95ce6d7a958a24da9af3

============opinion 1 (true)
ballot1: https://explorer.zetachain.com/cosmos/tx/CA957EA842A159BD7EFFFF2CBE2FCCC477D56A9B6825E5D5376D318B0CC2CE9D
ballot2: https://explorer.zetachain.com/cosmos/tx/4E85C88B6265A1F521791E35888E2D3EB18981AA417092AD231EB1D0BF81D9AE
ballot3: https://explorer.zetachain.com/cosmos/tx/7FB96C2F1AE241C3B5420453677F3ACFDD951EA7E6C07CECF0F88557BDAE7588
ballot4: https://explorer.zetachain.com/cosmos/tx/5E263B51327200CE9895A4D9CE5B49F4A16764E76ED9919D7309EDEEC77139F6
ballot5: https://explorer.zetachain.com/cosmos/tx/BF9DF68FFCBA9D04209DE83654910B58B72D83E3E8347DF65A96C42EBA567B8C

============opinion 1 (false)
ballot6: https://explorer.zetachain.com/cosmos/tx/CF5D35558BE7274C1CD67D848544B16371898492277349905A3868E28B382E1C
ballot7: https://explorer.zetachain.com/cosmos/tx/9A163214806D752558E637A7836EB57479C6C6C63C02928D5752891C9B2599E6
ballot8: https://explorer.zetachain.com/cosmos/tx/D1B448DFBCAE10659393653BF375648CB822812B7DCA7890217D34EF4B5BA223

**Comment by ws4charlie** [comment]
This [PR](https://github.com/zeta-chain/node-private/pull/64) fixed the issue
