### ISSUE TITLE
Makes cross-chain fee charging reasonable: withdrawal fee and deposit fee

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1404]
The background:

Bitcoin transaction fee is proportional to the size of the transaction in bytes and both inputs and outputs contribute to the size of the transaction.

1. **Input part**: The more UTXOs TSS address spends, the more expensive the transaction fee will be.
2. **Output part**: The more new UTXOs TSS address creates, the more expensive the transaction fee will be.

When user withdraws BTC from Zetachain, the TSS needs to sign a Bitcoin outTx to send BTC to user's Bitcoin address.
Typically, the TSS just needs two UTXOs to do the work: the nonce-mark UTXO and the UTXO that contains enough BTC amount to pay the user.

**There are two problems in the above approach:**

1. The number of UTXOs owned by the TSS will grow over time because Bitcoin users keep depositing BTC to TSS address.
         `1.1>` On TSS migration, the TSS needs to spend all its UTXOs to move the funds to the new TSS address. This could be a time-consuming and expensive process.
	 `1.2>` Moreoever, users can also spam the TSS address with dust-value deposits.
2. On big-value withdrawals, the TSS may need to spend more than two (unpredictable number) UTXOs to pay the user, which causes not only higher transaction fee but also TSS key-signing timeout.

**The solutions to the above problems are:**

1.  UTXO consolidation: the TSS will constantly consolidate its UTXOs by spending small-value UTXOs to itself.
     After consolidation, the TSS will have fewer UTXOs (<= 10), making TSS migration and big-value withdrawal cheaper and faster.

2.  Separate deposit fee from withdrawal fee:
     `2.1>` User who deposits UTXO to TSS address must pay a deposit fee. The deposit fee is used to cover the input part of outTx transaction fee.
                 &emsp;&emsp;This is because the deposited UTXO will be spent by the TSS in the future and spending a UTXO costs fee.
                 &emsp;&emsp;This also discourages users from spamming the TSS address with dust-value deposits.
          
     `2.2>` User who withdraws BTC from Zenchain must pay a withdrawal fee. The withdrawal fee is used to cover the nonce-mark part (input & output) and output part of outTx transaction fee.

https://zetachain.slack.com/archives/C04GM8RV5E3/p1700072284621409?thread_ts=1700071323.699129&cid=C04GM8RV5E3

**Comment by brewmaster012** [comment]
how is the consolidation tx scheduled?

**Comment by ws4charlie** [comment]
> how is the consolidation tx scheduled?
Consolidation tx is now scheduled on every outTx. There is no additional/separate schedule for consolidation.

**Comment by brewmaster012** [comment]
Every bitcoin outtx causes two bitcoin txs?
