### ISSUE TITLE
Native SDK Local Network State Export

### ISSUE THREAD

**Issue by gzukel** [zeta-chain/node#1422]
The way generating a state export for upgrade path testing works currently is a bit flawed. We take a state export then we use python to manipulate a json file to try and prepare a state for starting a single node network. This isn't exactly reliable or efficient.

What makes more sense is giving the cli a function that can prepare a mainnet state export using the native CosmosSDK for starting local single node testing networks derived from the mainnet state. 

That way the SDK can manipulate the genesis as it writes it to be able to start a local network with a provided account address as the validator address to assign the power to start the network too.

Also, we should examine the state export code when doing this to try and reduce or limit its speed to reduce resources required to take a state export instead of trying to do it as fast as possible limit the memory usage and keep the export within a set of bounds to have it be more predictable.

**Comment by CharlieMc0** [comment]
- State Export Modifications
    - Need to pass in new values for:
        - TSS Address
        - Observer List
        - Validators
        - Connector/Token Contracts
        - TSS Nonce
        - 
    - Goal is to create new standalone networks w/ external connections from a state export
        - https://excalidraw.com/#room=c3a7a28febd88a3c52d7,LB8d7K36zgvS_X2uHe5oRw

**Comment by kingpinXD** [comment]
The following are already added when we create a new genesis, 
- Observer List
- Validators
This happens through the `zetacored add-observer-list observers.json` command 

The same command takes an additional option input for `tss-pubkey` 
Example : `zetacored add-observer-list observers.json --keygen-block=0 --tss-pubkey="zetapub1addwnpepq28c57cvcs0a2htsem5zxr6qnlvq9mzhmm76z3jncsnzz32rclangr2g35p"` . Which can be used to add the following details 
- TSS Address
- TSS Nonce

Connector and token contracts are set through chain params,which can be updated via `MsgUpdateChainParams`
