### ISSUE TITLE
Indexer data upgrades for updated Explorer UI

### ISSUE THREAD

**Issue by bbbeeeee** [zeta-chain/node#145]
We are aiming to support the following data ideally through the Hasura endpoint (data from the Indexer):

- Transactions (internal and external)
    - Source/Destination Transaction Data Parsing and Display
    - Live tracking of source/zetachain/destination status (Hasura subscriptions) in the UI
    - Transaction types (Send/Cross-Chain, internal transaction labels/types)
- Blocks
    - Transaction list per block
- Validator data
    - Recent blocks per validator
- Network Data
    - Transactions per network (i. e. filter transactions by networks)
- Validator Details
- Address Details (Source/Destination Address, Validator/ZetaChain Address)
    - With related transactions
- Connector Address + Gas Amounts

Could we try to support all of the above? As well, if anything is not feasible or needs clarification (or should come from somewhere else), it would be good to hash out those details here!

**Comment by lumtis** [comment]
Looks no longer relevant, please feel free to reopen otherwise
