### ISSUE TITLE
`common`: remove usage of `https://rpc.ankr.com/eth_goerli` dialing for testing

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1458]
We use the RPC url `https://rpc.ankr.com/eth_goerli` for header testing in `common/ethereum` and `testutil/common/sample`.

Unit tests should use static data to ensure predictability (it also delays teast completion). We should use a hardcoded block and remove the rpc endpoint

**Comment by ptdatta** [comment]
Hey @lumtis , Can I give it a try?

**Comment by lumtis** [comment]
Sure, thank you for the interest👍

**Comment by ptdatta** [comment]
Should I hardcoded the transactions also?

**Comment by lumtis** [comment]
We can sue hardcoded value in the `sample` package, yes.

**Comment by ptdatta** [comment]
Hey @lumtis can you please help me 
```
func GenerateHardCodedBlock(t *testing.T) *types.Block {
	var transactions []*types.Transaction
	for i := 0; i < 5; i++ {
		tx := types.NewTransaction(uint64(i), common.BytesToAddress(sdk.AccAddress(ed25519.GenPrivKey().PubKey().Address()).Bytes()), big.NewInt(1000), 21000, big.NewInt(1000000000), nil)
		transactions = append(transactions, tx)
	}
	t.Logf("%+v", transactions)
	block_1 := types.NewBlock(
		&types.Header{Number: big.NewInt(314)},
		transactions,
		nil, nil, nil,
	)
	return block_1
}
``` 
it generates the transactions but on adding them to the block it gives this error
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6cb9ac]

goroutine 34 [running]:
testing.tRunner.func1.2({0xd9f0e0, 0x16774d0})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0xd9f0e0, 0x16774d0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/ethereum/go-ethereum/core/types.DeriveSha({0x10ad130, 0xc00051e228}, {0x0, 0x0})
        /home/parthib/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/types/hashing.go:88 +0x6c
github.com/ethereum/go-ethereum/core/types.NewBlock(0xc000191860?, {0xc000532900?, 0x5, 0x8}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...)
        /home/parthib/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/types/block.go:202 +0x119
github.com/zeta-chain/zetacore/common/ethereum.GenerateHardCodedBlock(0xc000588680)
        /home/parthib/Desktop/OSS/Zetachain/node/common/ethereum/proof_test.go:150 +0x539
github.com/zeta-chain/zetacore/common/ethereum.TestProofGeneration(0xc000588680)
        /home/parthib/Desktop/OSS/Zetachain/node/common/ethereum/proof_test.go:20 +0x36
testing.tRunner(0xc000588680, 0xfc8620)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
exit status 2
```
Am I moving the right direction?

**Comment by lumtis** [comment]
> Hey @lumtis can you please help me
> 
> ```
> func GenerateHardCodedBlock(t *testing.T) *types.Block {
> 	var transactions []*types.Transaction
> 	for i := 0; i < 5; i++ {
> 		tx := types.NewTransaction(uint64(i), common.BytesToAddress(sdk.AccAddress(ed25519.GenPrivKey().PubKey().Address()).Bytes()), big.NewInt(1000), 21000, big.NewInt(1000000000), nil)
> 		transactions = append(transactions, tx)
> 	}
> 	t.Logf("%+v", transactions)
> 	block_1 := types.NewBlock(
> 		&types.Header{Number: big.NewInt(314)},
> 		transactions,
> 		nil, nil, nil,
> 	)
> 	return block_1
> }
> ```
> 
> it generates the transactions but on adding them to the block it gives this error
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
>         panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6cb9ac]
> 
> goroutine 34 [running]:
> testing.tRunner.func1.2({0xd9f0e0, 0x16774d0})
>         /usr/local/go/src/testing/testing.go:1526 +0x24e
> testing.tRunner.func1()
>         /usr/local/go/src/testing/testing.go:1529 +0x39f
> panic({0xd9f0e0, 0x16774d0})
>         /usr/local/go/src/runtime/panic.go:884 +0x213
> github.com/ethereum/go-ethereum/core/types.DeriveSha({0x10ad130, 0xc00051e228}, {0x0, 0x0})
>         /home/parthib/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/types/hashing.go:88 +0x6c
> github.com/ethereum/go-ethereum/core/types.NewBlock(0xc000191860?, {0xc000532900?, 0x5, 0x8}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...)
>         /home/parthib/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.26/core/types/block.go:202 +0x119
> github.com/zeta-chain/zetacore/common/ethereum.GenerateHardCodedBlock(0xc000588680)
>         /home/parthib/Desktop/OSS/Zetachain/node/common/ethereum/proof_test.go:150 +0x539
> github.com/zeta-chain/zetacore/common/ethereum.TestProofGeneration(0xc000588680)
>         /home/parthib/Desktop/OSS/Zetachain/node/common/ethereum/proof_test.go:20 +0x36
> testing.tRunner(0xc000588680, 0xfc8620)
>         /usr/local/go/src/testing/testing.go:1576 +0x10b
> created by testing.(*T).Run
>         /usr/local/go/src/testing/testing.go:1629 +0x3ea
> exit status 2
> ```
> 
> Am I moving the right direction?

Sorry for the late reply, I missed your comment.

We should implemented a fix for the issue: https://github.com/zeta-chain/node/pull/1872
