### ISSUE TITLE
Backlog for issue: false block number in transaction's receipt for Goerli endpoint

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1466]
The Goerli endpoints somehow returned false block number in the receipt of outbound transaction.
![image](https://github.com/zeta-chain/node-private/assets/34498985/41e9a9e9-8718-432e-961c-773fa29bc1c4)
![image](https://github.com/zeta-chain/node-private/assets/34498985/8ed1cefa-54ba-4b89-84a1-fe3fd6c4cc69)

Based on observation, this misinformation happens when returned `isPending` status is `true`
![image](https://github.com/zeta-chain/node-private/assets/34498985/19d94fb4-6637-4dcc-a77c-371bbe5a0dff)

Check out [Datadog link](https://app.datadoghq.com/logs?query=service%3Azetaclientd%20confirmed%20but%20still%20pending%20&cols=host%2Cservice&context_event=AYxLj_ezAADE4g-GYpsJ3QBQ&index=%2A&messageDisplay=inline&refresh_mode=sliding&saved-view-id=2284468&storage=hot&stream_sort=time%2Cdesc&viz=&from_ts=1701472648241&to_ts=1702077448241&live=true) to see which zetaclients are getting this false misinformation.

**Comment by lumtis** [comment]
This seems to be an important issue to prioritize?

**Comment by ws4charlie** [comment]
The fixing commit (48d36db7b522328c13813b0904030fc8a6cfbf69) already exists in develop branch.
