### ISSUE TITLE
Should avoid unnecessary keysign for a same outtx nonce if the corresponding tx is already broadcasted and pending in external chain

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1478]
For example, we got stuck on this outTx because Goerli somehow didn't pick up and include it for 8 hours. https://goerli.etherscan.io/tx/0x23902b0c3b689e84994e96bd940918ccf888534d8e52f712c5ef3a3eed0008bf

In this case, TSS signers continued to schedule too many keysign and broadcasted unnecessary transactions
![image](https://github.com/zeta-chain/node-private/assets/34498985/490179e2-4064-42ea-87b4-2fe7c20d10cf)
https://app.datadoghq.com/logs?query=host%3Avalidator0-us-east-1-testnet%20service%3Azetaclientd%20on%20chain%20chain_name%5C%3Agoerli_testnet%20chain_id%5C%3A5%20nonce%20184993%20&agg_q=status%2Cservice&cols=host%2Cservice&context_event=AYw8QV0iAAAyYf4ErusvYgA1&index=%2A&messageDisplay=inline&refresh_mode=sliding&saved-view-id=2250519&sort_m=%2C&sort_t=%2C&storage=hot&stream_sort=time%2Casc&top_n=10%2C10&top_o=top%2Ctop&viz=&x_missing=true%2Ctrue&from_ts=1701877487839&to_ts=1701963887839&live=true

but none of these tx will be accepted by Ethereum as they are the same tx (not tx replacing).

**Comment by lumtis** [comment]
@ws4charlie any update on this issue?
