### ISSUE TITLE
`VerifyOutTxBody` for tx validation should use the right TSS address

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1485]
We currently retrieve the current TSS address to validate the Tx body
```
func (k Keeper) VerifyOutTxBody(ctx sdk.Context, msg *types.MsgAddToOutTxTracker, txBytes []byte) error {
	// get tss address
	tss, err := k.GetTssAddress(ctx, &observertypes.QueryGetTssAddressRequest{})
	if err != nil {
		return err
	}

```

The TSS address may change but we should always be able to validate the tx body at any point, unless we plan to stop all inbound and outbound and validate all txs before performing a TSS change, otherwise we should use TSS historical data depending on the block height (I think we don't have this mapping right now)

**Comment by kingpinXD** [comment]
Yes, we store a list of TSS addresses, which can be retrieved with the finalized block height.

**Comment by lumtis** [comment]
Closing since not considered for the time being. Keeping the EPIC open for tracking.
