### ISSUE TITLE
Omnichain: calling contracts on connected chain from ZetaChain

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1508]
Right now you can withdraw tokens to connected chains, but due to gas issues https://github.com/zeta-chain/node/issues/1430 you can't withdraw to a contract thus triggering execution of its logic (when gas token is withdrawn).

Being able to call a contract on a connected chain from ZetaChain and pass it arbitrary data would open a huge number of additional use-cases.

```solidity
IZRC20(targetTokenAddress).withdraw(recipientAddress, outputAmount, data);
```

**Comment by lumtis** [comment]
Linking this comment in the issue as it contains some context on the implementation: https://github.com/zeta-chain/node/issues/1430#issuecomment-1872258651

**Comment by lumtis** [comment]
Closing as integrated as part of the Smart Contract v2 feature set
