### ISSUE TITLE
Find a way to eliminate the 'voting on wrong ballot' problem (happened on Goerli)

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1535]
The receipt fetched from Goerli endpoint could contain wrong BlockNumber which lead to wrong ballots. We should find a reliable/way to avoid this in zetaclients at run time, instead of force restarting zetaclients to resume the voting.

**Comment by kingpinXD** [comment]
Hey, @ ws4charlie, can you link to some examples? 
Are there different receipts for the same TX hash?

If there are garbage ballots , we can consider a cleanup function for ballots on zetacore which can run once every X number of blocks

**Comment by ws4charlie** [comment]
Example of correct ballot: http://46.4.15.110:1317/zeta-chain/observer/ballot_by_identifier/0xef99263ce84e10b6edc6a4bc289f7689b87b73892f62f706b9a2138112d42865
Example of wrong ballot: http://46.4.15.110:1317/zeta-chain/observer/ballot_by_identifier/0x806f3e35635aaf886b076b693e2e7b82ad89eeb590d52201317d7845f4091fc5

Example txs that casted wrong ballot:
https://explorer.zetachain.com/cosmos/tx/88581E9895E5BEA02CA85F8B98C0CD8AB46393D6C4A86C1744BC765D299C83D2
https://explorer.zetachain.com/cosmos/tx/88581E9895E5BEA02CA85F8B98C0CD8AB46393D6C4A86C1744BC765D299C83D2
