### ISSUE TITLE
Retry revert transactions

### ISSUE THREAD

**Issue by lucas-janon** [zeta-chain/node#156]
Would be great to have a way to retry revert transactions that ran out of gas and weren't executed, before we launch on mainnet.

As you mentioned in our call @brewmaster012 UX isn't the most important variable to optimize for, so just sending a message directly to the protocol should work (that said, I'm not sure how we could be able to send ZETA without using an external chain).

**Comment by lumtis** [comment]
We now have a mechanism to retry with higher gas price when the gas price is too low. If not enough value in the cctx to revert it gets aborted, we will work to improve abort handling on ZetaChain
