### ISSUE TITLE
Separate messages for each required policy group

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1562]
https://github.com/zeta-chain/node/pull/1552#discussion_r1449091703

For simplicity and better maintainability, each message should have a single policy group requirement.

We should change it for `MsgUpdateCrosschainFlags` and list other message with different policy group requirements

**Comment by kingpinXD** [comment]
We can refactor into the following messages. 

```
// MsgDisableCCTXflags -> PolicyType_groupEmergency
// Disable inbound and outbound transactions

// MsgEnableCCTXflags -> PolicyType_groupOperational
// Enable inbound and outbound transactions

// MsgUpdateGasPriceFlags -> PolicyType_groupOperational
// Update gas price flags

```

**Comment by lumtis** [comment]
Yes, this can looks like this.

**Comment by kingpinXD** [comment]
Broke this down into issue #2244 and #2245

**Comment by kingpinXD** [comment]
Closing this issue , and working on the new issues listed above
