### ISSUE TITLE
failed to set up light client state provider

### ISSUE THREAD

**Issue by dwisyafriadi** [zeta-chain/node#1583]
I can start my node why ? 
this is log error i have

Jan 14 20:00:07 vmi1598449.contaboserver.net zetacored[23278]: {"level":"info","server":"node","module":"pex","time":"2024-01-14T20:00:07+01:00","message":"No addresses to dial. Falling back to seeds"}
Jan 14 20:00:07 vmi1598449.contaboserver.net zetacored[23278]: {"level":"info","server":"node","module":"p2p","address":{"id":"91efb62e89c49e933b530fc15a6b93468a395730","ip":"52.204.29.109","port":26656},"time":"2024-01-14T20:00:07+01:00","message":"Dialing peer"}
Jan 14 20:00:07 vmi1598449.contaboserver.net zetacored[23278]: {"level":"error","error":"failed to start state sync: failed to set up light client state provider: invalid TrustOptions: negative or zero height","time":"2024-01-14T20:00:07+01:00","message":"failed start tendermint server"}
Jan 14 20:00:07 vmi1598449.contaboserver.net zetacored[23278]: Error: failed to start state sync: failed to set up light client state provider: invalid TrustOptions: negative or zero height
Jan 14 20:00:07 vmi1598449.contaboserver.net zetacored[23278]: Usage:

**Comment by lumtis** [comment]
Are you still experiencing this issue @dwisyafriadi ?
