### ISSUE TITLE
The observed TSS address in bitcoin client is not automatically updated when TSS migration completes

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#1599]
**Currently** the observed TSS address is only queried from `zetacored` at startup. 
When TSS migration completes the new TSS address is not updated in the zetaclientd, unless a restart of zetaclientd is invoked. Failing to restart zetaclientd will lead to observing outdated old TSS address. 

**Desired**: zetaclientd should prompty updates its copy of *current active* tss address when it changes in zetacored.

**Comment by kingpinXD** [comment]
Zetaclient now automatically restarts on a TSS update 
https://github.com/zeta-chain/zeta-node/blob/7d93d5a87497b08dc65e04b697fcd862c03e5c10/zetaclient/maintenance/tss_listener.go#L35-L45

**Comment by kingpinXD** [comment]
@lumtis @brewmaster012  I dont think this is related to bitcoin in anyway ? 

Please reopen the issue if there is something missing from the current imnplementation
