### ISSUE TITLE
Add precompiled contracts for staking

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1600]
Making it possible to do native Cosmos SDK staking within Solidity contracts.

https://docs.evmos.org/develop/smart-contracts/evm-extensions/staking

https://github.com/evmos/evmos/tree/e244f16fe894f7477806c851c9346bd38673bbd8/precompiles/staking

**Comment by lumtis** [comment]
Closing in favor of keeping https://github.com/zeta-chain/node/issues/2403 as the feature integration tracker
