### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#162]
Upon launch, we'll limit the rate that zeta token can be transferred cross chain. Low first, and gradually increase. 

Need to support "scheduling of cctx to a future time", and mechanism to adjust parameters. 

* Rate of ZETA amount transferred for CCTXs/messaging
* Rate of outflow value (withdraw) from ZetaChain

## Proposed solution

```[tasklist]
### Tasks
```

**Comment by lumtis** [comment]
Closing in favor of https://github.com/zeta-chain/node/issues/1689
