### ISSUE TITLE
Add ZetaChain to Ledger

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1637]
https://developers.ledger.com/docs/device-app/clones/eth-app-update
```[tasklist]
### Prerequisites
- [x] Design icon https://linear.app/zetablockchain/issue/PD-5489/create-icons-for-ledger
- [x] Add mainnet RPC to https://chainlist.org/
- [x] Add ZetaChain to SLIP-0044 https://github.com/satoshilabs/slips/pull/1672
- [x] Create a PR in the Ledger repo https://github.com/LedgerHQ/app-ethereum/pull/529
```

**Comment by brewmaster012** [comment]
does the ethereum app on ledger not work with zetachain EVM?

**Comment by fadeev** [comment]
> does the ethereum app on ledger not work with zetachain EVM?

It does, but according to the Ledger team when interacting with ZetaChain it will show native token as ETH (instead of ZETA) and will show chain ID instead of a chain name.

**Comment by fadeev** [comment]
Icons:

![Ledger Stax_icon_32x32](https://github.com/zeta-chain/node/assets/332151/1e8b8567-8b83-47a6-a3e8-7c67f185e540)
![Ledger Stax_icon_64x64](https://github.com/zeta-chain/node/assets/332151/2874e000-29a3-4df8-bcd8-6c1073c157b0)
![Ledger Stax_icon_32x32](https://github.com/zeta-chain/node/assets/332151/e6f48710-b6f4-4d3c-ab24-d89ccd380e83)
![Ledger Stax_icon_64x64](https://github.com/zeta-chain/node/assets/332151/d82c25b6-978f-4a7a-abc6-1c9b25ace476)

**Comment by fadeev** [comment]
https://github.com/satoshilabs/slips/pull/1672

**Comment by lumtis** [comment]
I see it as completed in the tasks
