### ISSUE TITLE
`MsgRemoveForeignCoin`: rename `Name` field into `ZRC20Address`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1650]
`MsgRemoveForeignCoin` is used to remove a foreign coin (object tracking ZRC20s)

The message contains a field "Name" that represents the index. The actual index is the address of the ZRC20

`Name` field should therefore be renamed into `ZRC20Address`

**Comment by ptdatta** [comment]
Hey @lumtis Can I give it a try?

**Comment by lumtis** [comment]
Sure! Thanks for the interest

**Comment by mohitsethia** [comment]
Hi @lumtis , can I contribute to this?
