### ISSUE TITLE
`zetacore` : replace `require` testing package with `assert`

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#1696]

**Comment by lumtis** [comment]
I think we can group it with https://github.com/zeta-chain/node/issues/1697 since ZetaClient doesn't have many tests for now. Also, please, better to use `zetacore` and `zetaclient` labels instead of precising it in the title for triaging.

**Comment by kingpinXD** [comment]
Closing the issue , we have moved to using required on zetacore
