### ISSUE TITLE
Support forks and reorgs for the block header system

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#1723]
On the zetacored block header state, each external chain of block headers must form a single chain. 
This is too rigid as there are rarely cases that a incorrect block header will be selected which is re-org'ed. 
A more robust approach would be allow branches -- but have simple fork-choice rule to invalidate stale/re-org'ed branches. 

On the zetaclientd side, vote on proper block headers to form a chain.

**Comment by lumtis** [comment]
Can you add more description on the idea behind making add block header more robust?
What is the current issue with the current logic for adding block headers.

**Comment by lumtis** [comment]
Thanks for the description. That makes sense. Maybe the issue title can be `support forks and reorgs for the block header system`

**Comment by lumtis** [comment]
Closing since not considered for the time being. Keeping the EPIC open for tracking.
