### ISSUE TITLE
Ethereum will see the Dencun upgrade on March 13, before which we should prepare zetaclient to suport new transaction type

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1755]
**Describe the Issue**
`Dencun` upgrade introduced a new transaction type, `blob-carrying` transaction, to benefit layer-2 applications. We simply skip the new transaction type in Athens which is a temporary fix. We should be able to observe `blob-carrying` transactions if it's a gas token deposit to Tss address.

**Expected Outcome**
zetaclient should be able to parse and observe new transaction type without error.

**Comment by lumtis** [comment]
@ws4charlie this is a change in the ZetaClient? Why setting observer label?

I will see if a can create a calendar in the project board to set a time to complete the issue.

**Comment by lumtis** [comment]
Just removed mainnet label, we can delete it now that mainnet is launched
