### ISSUE TITLE
Omnichain swap contract failed to send ZETA on ZetaChain to recipient

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1775]
Source chain:

https://etherscan.io/tx/0x7c03a9b719a7ac039960f2f72c43ec8d00626e9218b6267257c6bb550be90642

Destination chain hash:

https://zetachain.blockscout.com/tx/0x0aff5e175db8b6f2c2f9f8e632294b10be9349b95dbad271480ad0f1bdd7bc14

This is how we sent the zeta in our contract:

```solidity
// withdraw WZETA to get aZeta in 1:1 ratio
WZETA.withdraw(outputAmount);
// transfer azeta
(bool sent, ) = payable(senderEvmAddress).call{value: outputAmount}("");
require(sent, "Failed to transfer aZeta");
```

**Comment by fadeev** [comment]
@andresaiello are there any issues with WZETA withdrawal and subsequent transfer?

**Comment by fadeev** [comment]
@andresaiello can you confirm that this looks like the right way to send native ZETA after withdrawing?

**Comment by lumtis** [comment]
Closing. I guess it's more an issue for protocol-contracts if it is still a problem
