### ISSUE TITLE
Write full specs for `WithdrawAndCall` feature

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1778]
**Describe the Issue**

Perform technical assessment and write full specs for the `WithdrawAndCall` feature.

The functionality would allow to perform a ZRC20 withdraw on ZetaChain on an external chain and perform a smart contract call, enabling wide-range of application.

The document should provide:
- The API of the new component to integrate
- Dependencies
- A list of tasks to be performed for the completion of the functionality (should be broken down into small tasks)
- Time estimation for the completion of the feature
- Difficulties to be encountered

**Comment by brewmaster012** [comment]
Is there a spec of how this would work?

Suppose i have a omnichain dapp on zevm that does a bunch of stuff and the call withdtawAndCall. It triggers a cctx that calls a contract on ethereum. Since its user specified contract, we should expect such call could revert. What happens then?

**Comment by lumtis** [comment]
No longer relevant https://github.com/zeta-chain/node/issues/2402
