### ISSUE TITLE
Move `cli/integrationtests/inbound_voter_test.go` and `cli/integrationtests/outbound_voter_test.go` into `keeper` package

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1788]
**Describe the Issue**
These tests are used to test the voting logic of inbound and outbound ballot as an integration test with a group of voter.
The current structure spins up a local network and use the CLI interface. Which makes debugging hard when the test no longer passes because only the CLI response is available.
Moving the test logic in the keeper package, use the test keeper implementation and use the keeper interface would simplify debugging.

We can still add CLI unit test to test the CLI interface (which is not used by ZetaClient in any case)

**Comment by lumtis** [comment]
@kingpinXD I may think you worked on the these tests? Would you have strong opposition from moving those to `keeper`? Do we have any benefits of using the CLI interface?

**Comment by kingpinXD** [comment]
No, I think it's a good idea to move these tests to the keeper .

**Comment by lumtis** [comment]
Completed
