### ISSUE TITLE
Consensus Versioning and Upgrades

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#180]
**Problem**: we don't have consensus versioning yet so when we change parts of zetacore that affects consensus rules, upgrading existing network may cause consensus failures and new full-node cannot sync up. 

**Solution**: 

* Cosmos SDK upgrade module
* Custom solution that retains all versions of the msg handlers and maintain current version as part of the zetacore state. 

**Factors to consider**: 
* Code/operation Footprint
* What happens when we change protobuf definition of state variables or msgs? 
* Impact of future CosmWasm module?

**Comment by lumtis** [comment]
Closing as it looks no longer relevant.
