### ISSUE TITLE
BTC testnet transaction not being tracked

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1808]
https://blockstream.info/testnet/tx/ff7c41280b1bf685c476625dfc158d3c17e7333bcf3cc47e259813f6492bcd78

**Comment by fadeev** [comment]
@brewmaster012 does it look like there is anything wrong with this tx?

**Comment by lumtis** [comment]
@kevinssgh can the script be used with this transaction?

**Comment by 1337-ishaan** [comment]
@brewmaster012 can you confirm?

**Comment by fadeev** [comment]
@1337-ishaan the problem is that the deposited amount is less than the BTC deposit fee. You can learn more about depositing BTC to ZetaChain here:

https://www.zetachain.com/docs/developers/tokens/zrc20/#depositing-native-gas-tokens-as-zrc-20

BTC deposits should be higher than the BTC deposit fee, which is around 0.00000136 BTC (estimated value).

**Comment by 1337-ishaan** [comment]
@fadeev, the mentioned fees is per byte?

**Comment by 1337-ishaan** [comment]
https://live.blockcypher.com/btc-testnet/tx/aa40305e28f5538e651d9e4c7f4091d9ba8a026266c6f11ce3b0178d3866d3ce/

Here is the transaction with higher deposit, still can't find cctx

pls have a look @fadeev .

**Comment by fadeev** [comment]
@1337-ishaan 

```
npx hardhat cctx aa40305e28f5538e651d9e4c7f4091d9ba8a026266c6f11ce3b0178d3866d3ce 
✓ CCTXs on ZetaChain found.

✓ 0x2820ed5d0667608c757e0127e286e3701eed53d4bac2a951e978b1597ce4920b: 18332 → 7001: Reverted (can't call a non-contract address)
```

**Comment by fadeev** [comment]
> @fadeev, the mentioned fees is per byte?

No, it's a total fee.
