### ISSUE TITLE
Cleaning up unused functions and variables and add more documentation

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1813]
`emissions` module has some unused variables and methods that makes understanding the code complicated.
Example not used:
- https://github.com/zeta-chain/node/blob/6c0e0bba0e1c03e916cbf05667b22f44b501f555/x/emissions/types/keys.go#L28
- https://github.com/zeta-chain/node/blob/6c0e0bba0e1c03e916cbf05667b22f44b501f555/x/emissions/keeper/block_rewards_components.go#L68

We should remove all these unused components.

We should also add more documentation for the variables and functions. Example: 
- How this value has been calculated: https://github.com/zeta-chain/node/blob/6c0e0bba0e1c03e916cbf05667b22f44b501f555/x/emissions/types/keys.go#L55
- What does this function do: https://github.com/zeta-chain/node/blob/6c0e0bba0e1c03e916cbf05667b22f44b501f555/x/emissions/keeper/block_rewards_components.go#L10
- ...

**Comment by kingpinXD** [comment]
Related 
https://github.com/zeta-chain/protocol-private/issues/96

**Comment by kingpinXD** [comment]
duplicate : https://github.com/zeta-chain/node/issues/1852
