### ISSUE TITLE
Consider lowering BSC withdraw fee on testnet

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1820]
Right now the fee is very high (0.25 BNB) which makes it difficult for developers to test cross-chain functionality.

Related message:

https://www.zetachain.com/docs/architecture/modules/fungible/messages/#msgupdatezrc20withdrawfee

I propose we submit a group proposal to substantially lower the fee.

**Comment by ronaldoguedess** [comment]
Please, make it low for purpose tests.

**Comment by ronaldoguedess** [comment]
It will give developers more flexibility, as ether is slow to interact... Plus, it do not make sense charge high fee on BNB.

**Comment by lumtis** [comment]
The protocol flat fee has been decreased to `0.05BNB`
