### ISSUE TITLE
refactor: consider having a separate ticker/thread(from TSS intx observation) for posting block headers

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#1847]
**Describe the Issue**
Here is the [current code](https://github.com/zeta-chain/node/blob/feat-observe-blob-transaction/zetaclient/evm/evm_client.go#L1136) with the `TODO` notation. 

**Expected Outcome**
Instead of embedding block header posting logic in function `observeTssRecvd`, we should have a separate/dedicated job or thread for that purpose.

**Reason**
The job of `observeTssRecvd` scans incoming txs to TSS address in block range `[startBlock, toBlock]` which will not be always the correct range for block header posting. Adding block header to zetacore is a very sequential process in zetacore and usually slower than inbound tx observation which is posting discrete votes. Decoupling the two makes code more maintainable and less error prone.

**Comment by lumtis** [comment]
Duplicate #2204
