### ISSUE TITLE
Possibly missed observations on Bitcoin

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#1907]
https://blockstream.info/testnet/tx/087c5c1396a680cdd162c7323c0837f0ddbfe804b49052c03ac0dc6cf00b84ef

https://blockstream.info/testnet/tx/01adcad5e2660103ad75900f62897927aa40d9c7f8e90b651aa00cad8698130a

**Comment by fadeev** [comment]
```
btc deposit amount 0 in txid 087c5c1396a680cdd162c7323c0837f0ddbfe804b49052c03ac0dc6cf00b84ef is less than depositor fee 1.496e-05
```

The second CCTX was reverted:

https://zetachain-testnet-api.itrocket.net/zeta-chain/crosschain/cctx/0xcae08ab42b83fde9dfcca15285a9c3c5ed0c6e2adc4e05db1c154d12955fa517

**Comment by fadeev** [comment]
## Reverted TX

https://blockstream.info/testnet/tx/01adcad5e2660103ad75900f62897927aa40d9c7f8e90b651aa00cad8698130a?expand

<img width="1840" alt="Screenshot 2024-03-18 at 20 31 47" src="https://github.com/zeta-chain/node/assets/332151/3ec52f83-27cd-44ea-ad93-53486cb4840f">

## Example of a successful TX

https://blockstream.info/testnet/tx/3c2eeee38fafbfbcdceca0d595c1433c48c738aaa6e1df407a681aeeeb1da3d6?expand

<img width="1840" alt="Screenshot 2024-03-18 at 20 32 07" src="https://github.com/zeta-chain/node/assets/332151/f32f9d20-3814-4276-9c67-e0c75162cdbe">

@ws4charlie could the issue be in the format of the OP_RETURN?

**Comment by fadeev** [comment]
@adi44 when sending the tx through XDEFI, did you put `hex::` in the memo field before the actual memo? Like in this example: https://www.zetachain.com/docs/developers/omnichain/tutorials/bitcoin-frontend/

**Comment by fadeev** [comment]
Note to self:

> The depositor fee is based on the average fee rate in that containing block 2582482 . If we look at this block using below link https://mempool.space/testnet/api/v1/blocks/2582482
We'll see "avgFeeRate":11 in the result. So, the depositor fee is calculated as
68vB * gasPriceMultiplier (which is 2) * 11 === 1.496e-05

I need to add this to the docs.

**Comment by SebaBau** [comment]
@fadeev this is transaction with I assume correctly encoded memo and still I don't received tokens on Zetachain Testnet.

https://blockchair.com/bitcoin/testnet/transaction/124d23127a54c5df8f13c2898542b567ca4c85d8370ef97d7363ce484f424b9f

**Comment by fadeev** [comment]
@SebaBau the amount 0.000001 is lower than the depositor fee 1.496e-05.

**Comment by SebaBau** [comment]
> @SebaBau the amount 0.000001 is lower than the depositor fee 1.496e-05.

@fadeev where I can see current depositor fee ?

**Comment by fadeev** [comment]
> > @SebaBau the amount 0.000001 is lower than the depositor fee 1.496e-05.
> 
> @fadeev where I can see current depositor fee ?

Can be calculated using the formula: https://github.com/zeta-chain/node/issues/1907#issuecomment-2004252149
