### ISSUE TITLE
`zetacore` : `crosschain` Use a single function to create a new cctx

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#1909]
The cross-chain module should have only one function in the types package which should be used to create a new cctx from a vote message.

The following logic should be refactored 

https://github.com/zeta-chain/zeta-node/blob/8e35f5bf763c170ffc3b223feb07f7a0b0ff936f/x/crosschain/keeper/msg_server_migrate_tss_funds.go#L84-L121

https://github.com/zeta-chain/zeta-node/blob/8e35f5bf763c170ffc3b223feb07f7a0b0ff936f/x/crosschain/keeper/msg_server_whitelist_erc20.go#L116-L153

**Comment by lumtis** [comment]
Completed
