### ISSUE TITLE
Running zetacored version doesn't include the full version

### ISSUE THREAD

**Issue by julianrubino** [zeta-chain/node#1937]
**Describe the Bug**

when I run zetacored version on the new binary it retrieves the version in a shorted way.
```
./zetacored  version
15
```

this is how was looking on the previous ones:
```
./zetacored version
14.0.1
```

I think that this shouldn't affect us in any way, but we want the full version to identify which minor/patch version are we running.

**To Reproduce**
```
./zetacored version
v15
```

**Expected Behavior**
```
./zetacored version
15.0.0
```

**Environment (please complete the following information):** Athens
- OS -> Linux
- Version used -> v15.0.0

**Comment by lumtis** [comment]
Has been fixed
