### ISSUE TITLE
Document rpc methods support

### ISSUE THREAD

**Issue by skosito** [zeta-chain/node#1950]
**Describe the Issue**
Some rpc methods are not fully supported yet for some transactions (eg: https://github.com/zeta-chain/node/issues/1383). 
Purpose of this task is to research and document current support for most important rpc methods.

**Expected Outcome**
Doc that can be referenced to track and communicate rpc methods support.

**Comment by lumtis** [comment]
@skosito as discussed I think we can create a new issue listing the methods with issue as an output for this task?
