### ISSUE TITLE
Support `EIP-1559` transactions with ZetaClient

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1952]
**Describe the Issue**
Send `EIP-1559` transactions using fee market mechanism on ZetaClient and prevent using legacy transactions

Context: https://github.com/zeta-chain/node/pull/1900#discussion_r1539131000

**Comment by lumtis** [comment]
@ws4charlie would you see an issue with using EIP-1559 transactions with ZetaClient?

**Comment by ws4charlie** [comment]
Here is a comparison of a legacy transaction and an EIP-1559 transaction:
<br />

**Transaction fee:**

-   A legacy transaction fee is calculated as: `gasPrice x gasUsed`

-   An EIP-1559 transaction fee is calculated as: `(baseFee + gasTipCap) x gasUsed`, see: [metamask doc](https://support.metamask.io/transactions-and-gas/gas-fees/how-to-estimate-the-gas-fee/#:~:text=As%20of%20EIP%2D1559%2C%20the,x%20units%20of%20gas%20used))

-   From the perspective of CCTX fee charging: `gasPrice  == baseFee + gasTipCap`


    In order to not touch the CCTX fee charging logic, zetaclient can simply post (`baseFee + maxPriorityFeePerGas`) as a replacement of `gasPrice` for EIP-1559 enabled chains.
<br />
<br />

**Transaction building:**

- A legacy transaction requires: `gasPrice`, `gasLimit`
![image](https://github.com/zeta-chain/node/assets/34498985/6b20f291-a4ef-4beb-aab7-3dc249cbce1c)
- An EIP-1559 transaction requires: `gasTipCap`, `maxFeePerGas`, `gasLimit`
![image](https://github.com/zeta-chain/node/assets/34498985/384f83a0-692a-4c54-aa5b-f6f2e5863e18)
- Sending a EIP-1559 transaction without explicit `gasTipCap` or `maxFeePerGas` will result in error (in live tests).

  Where to get deterministic numbers of `gasTipCap` and `maxFeePerGas` when signing a TSS transaction?

- Remember the equation `gasPrice == baseFee + gasTipCap`. If `gasTipCap` becomes a field of CCTX outbound parameter, the zetaclient can then calculate `baseFee` as
`gasPrice - gasTipCap`.

- The `maxFeePerGas` is the upper limit of gas price that the sender is willing to pay. The estimation of `maxFeePerGas` can be done by
`maxFeePerGas = gasTipCap + baseFee * 2`

  See this gas fee estimation article: https://www.blocknative.com/blog/eip-1559-fees
  See ChainSafe's gas estimator for its bridge: https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/calls/evmgaspricer/london.go#L65


  The current model of a CCTX outbound parameter only contains `gasPrice` and `gasLimit`. To support EIP-1559, a new field `gasTipCap` needs to be added.
<br />
<br />


**Pending Transaction replacement:**


  A legacy transaction can be replaced by a new transaction with
  - same `nonce`
  - a higher `gasPrice`


  An EIP-1559 transaction can be replaced by a new transaction with
  - same `nonce`
  - a higher `gasTipCap`, at least 10% higher
  - a higher `maxFeePerGas`, at least 10% higher

  See Alchemy doc: https://docs.alchemy.com/docs/retrying-an-eip-1559-transaction
  See go-ethereum: https://github.com/ethereum/go- ethereum/blob/87246f3cbaf10f83f56bc4d45f0f3e36e83e71e9/core/txpool/legacypool/list.go#L323
  and https://github.com/ethereum/go-ethereum/blob/87246f3cbaf10f83f56bc4d45f0f3e36e83e71e9/core/txpool/legacypool/legacypool.go#L146


  When the gas stability pool kicks in:
  -both `gasPrice` and `gasTipCap` needs to be increased by some percentage >= 10%
  -again, remember the equation `gasPrice == baseFee + gasTipCap`
  -zetaclient will calculates new baseFee as: `gasPrice - gasTipCap`
  -zetaclient will calculates new maxFeePerGas as `gasTipCap + baseFee * 2`
  -zetaclient will broadcast updated transaction with new `gasTipCap` and `maxFeePerGas`.

**Comment by kingpinXD** [comment]
Is the formula `maxFeePerGas = gasTipCap + baseFee * 2` a standard ? Based on the docs it provides a 6 block buffer . 
Should we increase that for some tx's like migration tx ? 

Same for the gas tip , do you think that should be higher for tx's which are more important for the network ?

**Comment by ws4charlie** [comment]
> Is the formula `maxFeePerGas = gasTipCap + baseFee * 2` a standard ? Based on the docs it provides a 6 block buffer . Should we increase that for some tx's like migration tx ?
> 
> Same for the gas tip , do you think that should be higher for tx's which are more important for the network?

I think it's fin. We already have the mechanism of replacing/retrying a TSS transaction.
