### ISSUE TITLE
Implement `verifyInTxBody` for Bitcoin transactions

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1993]
**Describe the Issue**
The function `verifyInTxBody` used to verify the body of the tx when adding a in tracker in a permissionless way is only implemented for EVM chain.

The implementation needs to be added for Bitcoin, it is already implemented for `VerifyOutTxBody`

**Comment by jacksoom** [comment]
Hi teams .I want to contribute this issue. pls help me review these verification conditions

verification conditions
1： first output must be addressed to the TSS Bitcoin address.
2：The second output must be a memo output, i.e. OP_RETURN PUSH_x [DATA]. This output must be less than 80 bytes.
3：rawtx.hash == msg.TxHash

cond 1/2 come from zetachain docs.  
Q: Does the BTC inbound transaction contain multiple cointypes?  btc/gas

**Comment by lumtis** [comment]
Closing since not considered for the time being. Keeping the EPIC open for tracking.
