### ISSUE TITLE
`OutTxTracker`: rename `TxHashList` into `TxHash`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#1995]
Note: Let's finish https://github.com/zeta-chain/node/pull/1976 first as it does refactoring in the out tx tracker logic

**Describe the Issue**
In the proto file for outtxtracker: 
```
message OutTxTracker {
  string index = 1; // format: "chain-nonce"
  int64 chain_id = 2;
  uint64 nonce = 3;
  repeated TxHashList hash_list = 4;
}
```
It doesn't make sense to call `TxHashList` since this is the element of the list. Should be renamed `TxHash`

**Comment by mohitsethia** [comment]
Hi, Can I contribute to it?

**Comment by mohitsethia** [comment]
Hi @lumtis , I have created this PR for refactoring (renaming to be more specific). Can you please help reviewing it?
https://github.com/zeta-chain/node/pull/2476
