### ISSUE TITLE
Rename all `outTx` mentions as `outbound` and all `inTx` as `inbound`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2011]
**Describe the Issue**
There are place were we use both of these terms for the same representation. We should do some renaming for consistency.

I think `outbound` and `inbound` are nicer names

**Comment by ws4charlie** [comment]
Just put a bit more background here. The `inTx` and `outTx` are abbreviations for `inbound transaction` and `outbound transaction`. Zetaclient also uses in logging, for instance `confirmed outtx hash: 0xd2eba..... for chain 1 nonce 9718`. If there are places to indicate `inbound/outbound transaction`, the `intx/outtx` will probably still one of good choices.

**Comment by lumtis** [comment]
> Just put a bit more background here. The `inTx` and `outTx` are abbreviations for `inbound transaction` and `outbound transaction`. Zetaclient also uses in logging, for instance `confirmed outtx hash: 0xd2eba..... for chain 1 nonce 9718`. If there are places to indicate `inbound/outbound transaction`, the `intx/outtx` will probably still one of good choices.

The is that inbound is a tx by definition, so it simplifies and remove ambiguity these are two different things
