### ISSUE TITLE
Reduce logic in `cmd/zetaclientd`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2019]
**Describe the Issue**
Currently `cmd/zetaclientd` has to much logic:
- Initialization of ZetaBridge, Signers, clients
- TSS generation
- Initiazation logic in `start.go`

We should keep the logic in `cmd` as minimal as possible. Making an interface interaction with packages in `zetaclient`
We also don't include the logic in `cmd` for the code coverage scope, which is decreasing coverage of potentially imporant logic.

We should move relevant logic in packages in ZetaClient and keep cmd minimal

**Comment by swift1337** [comment]
![image](https://github.com/user-attachments/assets/b6f793fa-4aaa-4ca4-b226-f51ddd7976b7)

## Simplify and consolidate files

We have too many of them, that creates distractions e.g. 

- `main.go` and `root.go` could be a single file
- Same for `utils` and `start_utils`
- Make sure there’s ONLY a single `init()` definition


## debug.go

Either refactor or drop `debug.go` (if not used) https://github.com/zeta-chain/node/blob/8d17118882f50003654e5d582f0b4049f913998f/cmd/zetaclientd/debug.go#L56

- Rename `debug.go` to `get_inbound_ballot.go`
- Remove logic for voting as it is supposed to only fetch the ballot
- Move the logic into the service layer, `cmd/` should only initialize the command and not contain business logic

## tss commands

Consolidate tss commands into a single `tss.go` https://github.com/zeta-chain/node/blob/9b704a5bf924b164ad1472f028323b8b59a102a0/cmd/zetaclientd/keygen_tss.go#L31

- Move tss generation logic into `zetaclient/tss/...`

**Comment by swift1337** [comment]
WIP

**Comment by swift1337** [comment]
start.go will be fixed in this issue https://github.com/zeta-chain/node/issues/3112
