### ISSUE TITLE
Upgrade test fails

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2054]
**Describe the Issue**
Currently testing in https://github.com/zeta-chain/node/pull/2051

Upgrade test is currently after after we try to run the first deposit after upgrade: the cctx is never mined

**Comment by lumtis** [comment]
The bug is because the ZetaClients don't restart

**Comment by gartnera** [comment]
Maybe we should run the advanced tests nightly and send slack notifications if they fail?

**Comment by lumtis** [comment]
Bug out of date
