### ISSUE TITLE
zetacored migrations run twice

### ISSUE THREAD

**Issue by gartnera** [zeta-chain/node#2077]
The zetacored migrations seem to be running twice. To reproduce, upgrade from `v14` to `v15` to a third version:

```
9:01PM INF Running upgrade handler for v15
9:01PM INF migrating module observer from version 6 to version 7
9:01PM INF Migrating observer store from v6 to v7
9:01PM INF Block rewards 9620949074074074074.074070733466756687 are greater than emission pool balance 0.000000000000000000
9:01PM INF executed block height=90 module=consensus num_invalid_txs=0 num_valid_txs=0 server=node

9:06PM INF Running upgrade handler for v1713982165
9:06PM INF migrating module observer from version 6 to version 7
9:06PM INF Migrating observer store from v6 to v7
9:06PM INF Block rewards 9620949074074074074.074070733466756687 are greater than emission pool balance 0.000000000000000000
9:06PM INF executed block height=250 module=consensus num_invalid_txs=0 num_valid_txs=0 server=node
```

The way that we choose which migrations to run seems to differ quite a bit from how cosmos suggests. First, there is this logic which means that we will always run the last migration from the observer module:

https://github.com/zeta-chain/node/blob/022ea57e25b4e0cb338b99bbd1c9e235f41ae954/app/setup_handlers.go#L47-L49

We also seem to be just ignoring the `x/upgrade` state version map and forcibly setting all modules to the latest version:

https://github.com/zeta-chain/node/blob/022ea57e25b4e0cb338b99bbd1c9e235f41ae954/app/setup_handlers.go#L19-L21

This has effect of always skipping migrations of any module other than `observer`. It apparently will also result in `InitGenesis` [not being called](https://docs.cosmos.network/v0.46/core/upgrade.html#genesis-state) for any new modules. See [`RunMigrations`](https://github.com/cosmos/cosmos-sdk/blob/release/v0.46.x/types/module/module.go#L460) for more info. If we just want to always skip `InitGenesis` for all modules, then the correct logic would look more like this:

```
for m, mb := range app.mm.Modules {
	if vm[m] == 0 {
		vm[m] = mb.ConsensusVersion()
	}
}
```

We also do not seem to be ever calling `app.UpgradeKeeper.SetModuleVersionMap(ctx, app.mm.GetVersionMap())` in `InitChainer` so the [upgrade state is never committed to the disk](https://docs.cosmos.network/v0.46/core/upgrade.html#in-place-store-migrations). Because of this, the `upgradeHandler` `fromVM` version map always returns 0.

**Comment by gartnera** [comment]
> so we should store this map, and remove consensus version - 1 part

All I think we can do for now is add the `app.UpgradeKeeper.SetModuleVersionMap(ctx, app.mm.GetVersionMap())` to v16 release, then untangle the rest in v17? We need one release where the version map gets committed before we can really change much it seems.

**Comment by kingpinXD** [comment]
The function is already called automatically I belive when the upgrade is applied 
https://github.com/zeta-chain/cosmos-sdk/blob/b3f95061fadeb51ffc731b60673c422ed5096948/x/upgrade/keeper/keeper.go#L365-L365

We can see the versions on mainnet here 
https://zetachain-mainnet-archive.allthatnode.com:1317/cosmos/upgrade/v1beta1/module_versions


However, I do agree manually decrementing the version is not the correct approach 
We should directly be sending the `VersionMap` received , the SDK basically uses the version from the Map vs the Version from Module.Connsesus version , to trigger the upgrade .

**Comment by kingpinXD** [comment]
THe issue with initi genesis , should also be solved because non existence modules would not exist in the fromVM , which is much more cleaner that using using some some weird logic like this . 
```
		for m, mb := range app.mm.Modules {
			if _, ok := vm[m]; ok {
				vm[m] = mb.ConsensusVersion()
			}
		}
```
Just posting this as an example .

**Comment by gartnera** [comment]
> The function is already called automatically I belive when the upgrade is applied

Ah I understand now the point of calling `app.UpgradeKeeper.SetModuleVersionMap(ctx, app.ModuleManager.GetVersionMap())` in `InitChainer` is to skip the migrations on brand new chain initialization.

So the consensus versions should already be committed to the disk on `v14`. I think we can remove the `- 1` now then?

**Comment by kingpinXD** [comment]
Yeah, exactly. We can remove the -1 for now. It should solve the following problems for us. 
- Remove the need to manually trigger migrations, Incrementing the consensus version in the module.go would automatically trigger migrations 
- Initi genesis would get called automatically if the module names are added to the `Added` section . 

I can create a PR and run some tests.
Related Issue : https://github.com/zeta-chain/node/issues/1824
