### ISSUE TITLE
Run upgrade tests in PR/mergequeue CI

### ISSUE THREAD

**Issue by gartnera** [zeta-chain/node#2134]
It seems like it's been very easy to break the upgrade tests. We need to run the upgrade tests in PR/mergequeue CI.

**Comment by lumtis** [comment]
Maybe we could add admin-test and upgrade-test in the merge queue and add two labels `skip-admin-test` and `skip-upgrade-test` to skip those?

These tests takes pretty long time, we shouldn't be blocked by these when changing updating a comment for example
