### ISSUE TITLE
Input field is empty in rpc methods response

### ISSUE THREAD

**Issue by skosito** [zeta-chain/node#2379]
**Describe the Bug**
Also check gasLimit and other empty fields. Reported for txByHash method, but applies to others as well.
Currently there is txData available in rpc methods in events, so check if it can be used for this.

**To Reproduce**
Check any of synthetic eth tx.

**Expected Behavior**
Input should be present in response.

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Comment by fadeev** [comment]
@skosito do we have an ETA on this?
