### ISSUE TITLE
Delay in Bitcoin Transaction Time

### ISSUE THREAD

**Issue by bhjiwonoh** [zeta-chain/node#2426]
**Describe the Bug**

Not a bug, but a performance-related inquiry.
If the transaction execution takes a long time, it may take around 20 blocks or more.

Here are some doubts/questions:
1) Have there been any previous reports of such cases? 
2) Is this issue only visible on the testnet? 
3) Are there any aspects we need to pay attention to when creating transactions?

Is there a way for an app builder to check the real-time status of asset transfer transactions between CrossChains? When delays occur, it could provide a better UX.

-----

Test Result

We tested 'sent-btc' in both directions: from Zeta to BTC and from BTC to Zeta.
The tests were conducted on the testnet.

index  |  from  |  to  |  duration(to-from)

Trial 1
	1	BTC (14:17:22) → ZETA (15:00:12) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x6936483d3d7e94669b0877a13ac07045e0828388fdccf7b7189fc02d5411d81c)) 43min.
	2	BTC (14:30:32) → ZETA (15:15:02) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0xd5e7c3816aacd765b82c5ef38591c79ba4df849573cbb5543b4140e885895da1)) 45min.
	3	BTC (14:30:32) → ZETA (15:15:02) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0xfea7ce93c31e5b61e36e38debdd447c22e8fcf6d39a620aa003c0c6d78015794)) 45min.
	4	ZETA (14:21:01) → BTC (14:30:32) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x02a6c584167346b5bea8406922d7d77cdeac59a47696c9f941b3c6c9bb755d02)) 10min.
	5	ZETA (14:22:11) → BTC (14:59:48) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0xd43b4767adbb76c1bb9d22f82a1bcbf0640708c8d000c43397b9697e15ef0dce)) 37min.
	6	ZETA (14:22:34) → BTC (14:59:48) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x8f60e4408bedc02d32f120b76baa0f17d37a81566f488bf0d70323d31182855d)) 37min.
Trial 2
	1	BTC (15:44:44) → ZETA (15:52:55) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x05c30832d0db4f7bec4b7baaac1b58a43bfed043a047ffa884f8ca874b70986e)) 68min.
	2	BTC (15:44:44) → ZETA (15:52:55) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x332ba108dbe17ef1ee6126b1a756b16829ffb095dbdbb1ea228bafeee34a7ff6)) 68min.
	3	BTC (15:44:44) → ZETA (15:52:55) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x8ee5c143d76d479d783c8414cee5aadb1b8b8beb42dd692f42c9ab11cb6c3cd8)) 68min.
	4	ZETA (15:49:15) → BTC (17:56:51) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x8fc529c0aa1fcad198c02bdb0888e881e228efb3ae05ae1aa7439e0181254192)) 127min.
	5	ZETA (15:49:33) → BTC (18:00:05) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0xa032ed93c4d6f8bfe0c1252b60a131746ec97288b420a9bdcc1e60873980053c)) 131min.
	6	ZETA (15:50:07) → BTC (20:28:09) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0xad7362f4d7352b05637dc25f6dc11a7aa592119fbb9793a4c7fbc8e8bd183f73)) 278min.
Trial 3
	1	BTC (17:47:15) → ZETA (18:04:06) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0xe2bc08a298807d452b20d31d51bf6150941a8a201261ca365c9e0c25622858ee)) 17min.
	2	BTC (17:47:15) → ZETA (18:04:06) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x18b091823d0e4bfa3a1569c1534299c62325a5e92039549e863cab4b0590b098)) 17min.
	3	BTC (17:47:15) → ZETA (18:04:06) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x04f81f7e3a7d271960f5e8b82b23fcd961c0c2301e85bc180c7c10564b2ccb5f)) 17min.
	4	ZETA (17:48:18) → BTC (20:28:09) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0xff14a3d1a736bd67662a8cbf1b9a79704259abb414f0e122cf2c582768d22892)) 160min.
	5	ZETA (17:49:04) → BTC (20:33:45) ([CCTX](https://athens.explorer.zetachain.com/cc/tx/0x4ef18b9c49126547704bf65e3ce4e45493c6ba052f8b12a25a0b4a0750549938)) 164min.
	6	ZETA (17:49:27) → BTC (20:46:33) (CCTX) 177min.

**To Reproduce**

1) BTC → ZETA TX
npx hardhat send-btc --amount 0.1 --memo 8923360f4323E3aF53B09C4e455248bB2AaA75C100000000000000000000000000000000000000010dF2da2a54AF3A47ba8859D1Bd64690ba69f1dD1 --recipient tb1qy9pqmk2pd9sv63g27jt8r657wy0d9ueeh0nqur

2) ZETA → BTC TX
Basic code written for _ZRC20 withdrawal_ for test

**Comment by lumtis** [comment]
I think this might happened because of high activity on the testnet and difficulty for observers to catch up with the block, we're in the process of moving to testnet4 and signet for more performance on the testnets
