### ISSUE TITLE
Adjust Operations Group Permissions 

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#2430]
**Describe the Issue**
We want to make sure we correctly categorize high risk messages based on the potential impact. 

Some of these messages need to be adjusted: https://github.com/zeta-chain/node/blob/0bcb422e614c3e1b2c565de83017c93538ff668c/x/authority/types/authorization_list.go#L10-L41

What is the impact when `MsgRemoveForeignCoin` is used? If it deletes the supply or takes an irreversible action should be moved to the Admin group 

`* MsgAddObserver` - Does this by itself cause any changes to the network or signing process? It should probably be moved to Admin 

**Expected Outcome**

All of these should move to the admin group and maybe the two described above based on your answers. 
- MsgEnableHeaderVerification
-  MsgRemoveChainParams
- MsgDeployFungibleCoinZRC20
- MsgRemoveForeignCoin
- MsgWhitelistERC20

**Comment by lumtis** [comment]
> -  MsgAddObserver - Does this by itself cause any changes to the network or signing process? It should probably be moved to Admin

I think it makes sense to move it as well as independently of the signing process, observer is a sensitive part of the network

> What is the impact when MsgRemoveForeignCoin is used? If it deletes the supply or takes an irreversible action should be moved to the Admin group

Delete the foreign coin object in the store but not the smart contract. I think we'll have to revise the process of for removing token and move this one in admin for now
