### ISSUE TITLE
create a setter method to allow observer to dynamically bind to a database for unit test

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#2437]
**Describe the Issue**
Currently the base observer expose interfaces of `OpenDB` and `LoadDB` to allow unit tests to initialize the database and prepare data for testing.

If we could add a setter method to base observer (e.g. `WithDB`) to attach a given DB instance (or even a DB interface to be a `dependency-injection` style), unit tests will be much easier.

**Expected Outcome**
A description of what outcome you are seeking.

**Comment by swift1337** [comment]
Not relevant
