### ISSUE TITLE
Move restart logic from supervisor into the zetaclient directly

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#2455]
TSS migration needs the following restarts to happen for successful completion
- Restart when new keygen is set 
- Restart when TSS is generated 
- Restart when TSS is updated 

PResently this logic to shutdown the client is part of zeta supervisor , but can be moved to the  zetaclient binary

**Comment by lumtis** [comment]
@kingpinXD can we please add some description on each issues.
- Giving some details about the goal of the issue and reasoning behind it
- Add associated labels to simplify triaging

Same for
https://github.com/zeta-chain/node/issues/2446
https://github.com/zeta-chain/node/issues/2447
https://github.com/zeta-chain/node/issues/2455
