### ISSUE TITLE
Emit EVM related event when synthetic EVM tx revert

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2461]
**Describe the Bug**

No event to index the EVM transaction is emitted if a synthetic tx revert.

https://github.com/zeta-chain/node/blob/9a527f96cf71651d5b8ca243474e48e6b73a2dbd/x/fungible/keeper/evm.go#L744
https://github.com/zeta-chain/node/blob/9a527f96cf71651d5b8ca243474e48e6b73a2dbd/x/fungible/keeper/evm.go#L748

We should process this same logic when the tx revert to ensure they can be indexed in explorer
https://github.com/zeta-chain/node/blob/9a527f96cf71651d5b8ca243474e48e6b73a2dbd/x/fungible/keeper/evm.go#L794

**Comment by fadeev** [comment]
Note to self: this is a prerequisite for Tenderly being able to track calls from system contract to universal apps (specifically the ones that have been reverted).
