### ISSUE TITLE
Use retry package for queries on zetaclient

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#2492]
Use retry package when refactoring this logic to move into the zetaclient
https://github.com/zeta-chain/zeta-node/blob/8e1cfa7589055522045699077e2e7a11a24c6f36/cmd/zetaclientd-supervisor/lib.go#L186-L193

https://github.com/zeta-chain/zeta-node/blob/8e1cfa7589055522045699077e2e7a11a24c6f36/cmd/zetaclientd-supervisor/lib.go#L227-L234

**Comment by lumtis** [comment]
@kingpinXD can we give more details on the related part that need to be refactored?

**Comment by kingpinXD** [comment]
> @kingpinXD can we give more details on the related part that need to be refactored?

Yeah I will add in after the two pr;s I have are merged so that I have a clear idea of the refactor
