### ISSUE TITLE
Error: http2 frame too large when setting up TSS address stuck

### ISSUE THREAD

**Issue by GDdark** [zeta-chain/node#2566]
Run `zetae2e setup-bitcoin cmd/zetae2e/config/local.yml`
And Show logs `⚙️ setting up TSS address`

It's been more than half an hour, and it's not completed

**Comment by GDdark** [comment]
I print the logs, and it shows
![image](https://github.com/user-attachments/assets/313e238a-a08c-4300-9ff6-5da84a453963)

**Comment by GDdark** [comment]
FIx it 
Change 0.0.0.0 to localhost

![image](https://github.com/user-attachments/assets/6dc799be-a42c-4d48-b3cc-32ea4debf77f)

**Comment by CharlieMc0** [comment]
Closed by https://github.com/zeta-chain/node/pull/2582
