### ISSUE TITLE
Add support for restricted address for Solana network

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#2604]
**Describe the Issue**
Implementation would be similar to what we've already done for restricted EVM address and BTC address. When a restricted is detected in inbound, zetaclients should ignore (logic is there but there is no e2e test). When a restricted is detected in outbound, zetaclient should cancel the withdraw CCTX with some proper mechanism.

The task would involve:
1. ignore inbound when it involves restricted address. Unit test, E2E test.
2. cancel withdraw CCTX when it involves restricted address. Unit test and E2E test.

**Expected Outcome**
A description of what outcome you are seeking.

**Comment by lumtis** [comment]
Completed in https://github.com/zeta-chain/node/pull/2795
