### ISSUE TITLE
Solana fee payer key improvement

### ISSUE THREAD

**Issue by ws4charlie** [zeta-chain/node#2606]
**Describe the Issue**
The Solana fee payer's private key is now a file (`~/.zetacored/solana-key.json`) containing plain text. Consider using a encrypted file and password to protect the key. The protection could be similar to what we've done for TSS key. Also, if necessary, we could use a better default path for the fee payer key? @CharlieMc0 

**Expected Outcome**
A description of what outcome you are seeking.

**Comment by lumtis** [comment]
The most ideal solution, short term, to me would be to move the signer out of the ZetaClient. The issue would be how to let ZetaClient communicate to the signer the tx to be sent?

As a long term solution we should have a model where a reward is paid to relayer to incentivize anyone to relay the tx

**Comment by ws4charlie** [comment]
The current flow:

1. Each outbound requires a TSS signature as authorization.
2. Once TSS signature is produced. Anyone (without permission) is able to wrap the signature into a Solana transaction to call Solana gateway program.
3. The step 2 is now done by the TSS signers using their own Solana private keys. To be specific, 9/9 of them will try to call 'withdraw' method on gateway, and only (and always) 1/9 will succeed.

Looks to me the TSS signers are the best candidates to do the job in step 2 because they're the only actors having immediate access to the produced TSS signatures.

For the cost of the Solana transaction, at least the Solana fee (now it's `0.000005` SOL static fee per outbound) of the transaction that calls the gateway `withdraw` needs to a refund back to the caller address (whoever it is).

For incentivization, it could be more a TBD.
