### ISSUE TITLE
Add created_at to CCTX status

### ISSUE THREAD

**Issue by CryptoFewka** [zeta-chain/node#2611]
**Is your feature request related to a problem? Please describe.**
Sometimes outbound CCTX trackers do not complete in a timely manner, and go undetected. 

**Describe the solution you'd like**
We would like to have a created_at datetime or created_at block number value set for each Outbound CCTX tracker. We would use this to detect when outbound TXs are still open longer than expected.

**Describe alternatives you've considered**
We can get close with the lastUpdate_timestamp value on the CCTX itself, but it is not 100% accurate.

**Comment by lumtis** [comment]
Can be part of https://github.com/zeta-chain/node/issues/1949 but since we're just adding a field, can also be added in the current object without migration.

Also CCTX.Status, already contains a `lastUpdate_timestamp` which might already serves this purpose?
