### ISSUE TITLE
feat(protos): About protobuf structure design

### ISSUE THREAD

**Issue by jacksoom** [zeta-chain/node#2641]
**Is your feature request related to a problem? Please describe.**
protobuf file: proto/zetachain/zetacore/pkg/proofs/ethereum/ethereum.proto 
Replace the array representation method with map.
Put/Delete/Has/Get Looks more suitable for map operation.  Arrays is not a  efficient structure

**Describe the solution you'd like**
```protobuf
message Proof {
  repeated bytes keys = 1;
  repeated bytes values = 2;
}
```

map

```protobuf
message Proof {
     map<bytes, bytes> proofs = 1; // key -> value
}
```
**Describe alternatives you've considered**
Null

**Motivation and Context**
Protobuf optimization

**Comment by lumtis** [comment]
It is generally advised not using maps in Cosmos SDK modules as iteration is not deterministic and can lead to consensus failiure.

**Comment by jacksoom** [comment]
> It is generally advised not using maps in Cosmos SDK modules as iteration is not deterministic and can lead to consensus failiure.

Cool
