### ISSUE TITLE
Error when upgrading to v19.0.0

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#2649]
> when we upgrade to v19.0.0, the program prompts "failed to load latest version: version of store crisis mismatch root store's version; expected 4284158 got 0; new stores should be added using StoreUpgrades. "Does the data need to be resynchronized?

**Comment by gartnera** [comment]
You cannot upgrade/run v19.0.0 until the upgrade height specified in the upgrade plan has been reached. Otherwise the required data migrations will not be run.
