### ISSUE TITLE
Fix ZRC-20 token symbols on mainnet

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#2679]
https://zetachain.blockpi.network/lcd/v1/public/zeta-chain/fungible/foreign_coins

```
USDC.BSC    ZetaChain ZRC20 USDC on BSC
USDC.ETH    ZetaChain ZRC20 USDC on ETH
BTC.BTC     ZetaChain ZRC20 BTC-btc_mainnet
PEPE.ETH    ZetaChain ZRC20 PEPE on ETH
BNB.BSC     ZetaChain ZRC20 BNB-bsc_mainnet
SHIB.ETH    ZetaChain ZRC20 SHIB on ETH
USDT.ETH    ZetaChain ZRC20 USDT on ETH
USDT.BSC    ZetaChain ZRC20 USDT on BSC
POL.POLYGON ZetaChain ZRC20 Polygon POL-polygon_mainnet
DAI.ETH     ZetaChain ZRC20 DAI on ETH
ETH.ETH     ZetaChain ZRC20 ETH-eth_mainnet
USDT.POL    ZetaChain ZRC20 USDT on POL
USDC.POL    ZetaChain ZRC20 USDC on POL
```

I see at least three problems:

* We're using "X.ETH" to refer to an asset from Ethereum. This is confusing, because ETH is a token. It should be "ETH.ETHEREUM"
* We have both "POL.POLYGON" and "USDT.POL"
* We have different chain labels in token names: "ZetaChain ZRC20 USDT on BSC" and "ZetaChain ZRC20 BNB-bsc_mainnet"

**Comment by lumtis** [comment]
Deuplicated for https://github.com/zeta-chain/node/issues/1734 (added in next milestone)
