### ISSUE TITLE
Upgrade `btcsuite` project-wise

### ISSUE THREAD

**Issue by swift1337** [zeta-chain/node#2728]
We need to upgrade `btcsuite` in the node and in `go-tss` to enable Taproot scripts. Currently, we have several different `btcd` package versions, which creates a headache in BTC dependencies in the project. We need to make it simpler.

Blocks https://github.com/zeta-chain/node/pull/2727

**Comment by brewmaster012** [comment]
i think this has been attempted more than once before, but 
there is some nasty dependency entanglement that is quite hard to resolve. 
it's very helpful upgrade but it might not be straightforward. 

Also a note to devops--upgrading btcd version also might require upgrading bitcoin core node software version.

**Comment by lumtis** [comment]
> i think this has been attempted more than once before, but there is some nasty dependency entanglement that is quite hard to resolve. it's very helpful upgrade but it might not be straightforward.
> 
> Also a note to devops--upgrading btcd version also might require upgrading bitcoin core node software version.

Was attempted in this branch: https://github.com/zeta-chain/node/tree/upgrade/btcd
