### ISSUE TITLE
`zetacore` : improve testing of zevm deposit

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#2731]
![image](https://github.com/user-attachments/assets/df7c795a-be72-4d45-b76d-e65f0a87805b)
![image](https://github.com/user-attachments/assets/4eca9bfd-9c04-4695-a857-10885a95f534)
![image](https://github.com/user-attachments/assets/75b84bb2-c449-42e4-b6bb-2301e0f291d3)

**Comment by lumtis** [comment]
Logic to be removed in the future with v2
