### ISSUE TITLE
Add a precompile allowing to map ERC20s into bank tokens

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2791]
**Describe the Issue**

Develop a precompile allowing to convert a ERC20 into a Cosmos bank token.

This extends the usage of the token allowing to use it in component using Cosmos native bank tokens.
- Most notably: allow to use the token as a staking reward using the distribution module

As ERC20s creation is permissionless, we might want to mechanism to be limited to some assts like only ZRC20s

Possible interface:

Contract is called `Bank`
```
function deposit(address zrc20, uint256 amount) // deposit the ZRC20 to be emitted as a Cosmos token on the user account
function withdraw(address zrc20, uint256 amount) // withdraw Cosmos tokens into ZRC20 in the user account
function balance(address zrc20, address user) uint256 // retrieve the balance of the user in Cosmos token for the ZRC20
```

**Comment by kingpinXD** [comment]
Would this allow querying ZRC20 balance using cosmos CLI  ?
if not , is that something we work on ?

**Comment by fbac** [comment]
> Would this allow querying ZRC20 balance using cosmos CLI ? if not , is that something we work on ?

The current design aims for:
- deposit() allows an user to deposit ZRC20 and receive cosmos coins with denom `zevm/ZRC20.Hex()`
- withdraw() allows an user to send `zevm/ZRC20.Hex()` and withdraw ZRC20.
- balance() checks the cosmos coin `zevm/ZRC20.Hex()` balance.
