### ISSUE TITLE
Add to foreign_contract_address to `zeta-chain/fungible/foreign_coins` endpoint

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#2818]
**Describe the Issue**
A clear and concise description of what the issue is.

The [zeta-chain/fungible/foreign_coins](https://zetachain.blockpi.network/lcd/v1/public/zeta-chain/fungible/foreign_coins) endpoints doesn't include the contract address used by a ZRC20 asset on the external chain. This makes it challenging for devs to collect all the important ZRC20 data in a single call. 

We have at least one partner who needs the ability to map ZRC20 Contract Addresses to the contract address on the foreign chain with one consolidated endpoint. 

**Expected Outcome**
Add a field like `foreign_contract_address` to the `zeta-chain/fungible/foreign_coins` endpoint. 

Example
```
{
"zrc20_contract_address": "0x05BA149A7bd6dC1F937fA9046A9e05C05f3b18b0",
"asset": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d",
"foreign_chain_id": "56",
"foreign_contract_address": "0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d", // NEW FIELD
"decimals": 18,
...
},
{
"zrc20_contract_address": "0x0cbe0dF132a6c6B4a2974Fa1b7Fb953CF0Cc798a",
"asset": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
"foreign_chain_id": "1",
"foreign_contract_address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", // NEW FIELD
...
},
````

**Comment by fadeev** [comment]
@CharlieMc0 how is the proposed field different from the existing “asset” field, which contains a token address on a connected chain?

**Comment by CharlieMc0** [comment]
Because I'm an idiot and totally missed that. So asset is the foreign asset. Got it. Closing this issue.
