### ISSUE TITLE
Make precompile contracts E2E test optional to run in the CI

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2832]
**Describe the Issue**
Since the precompiles are a scoped functionality influence the core crosschain workflow (at least for the current ones), I think we can move the precompiles E2E tests as optional using the CI matric like upgrade or admin tests

- Add a label `PRECOMPILE_TESTS`
- Only run the precompile tests in the CI and the label is set

**Comment by gartnera** [comment]
> influence the core crosschain workflow

The current tests seem to be fast and don't impact other tests. Are you referring to future functionality?

I think it would be good to keep some very basic validations in the default e2e if at all possible.

**Comment by lumtis** [comment]
> > influence the core crosschain workflow
> 
> The current tests seem to be fast and don't impact other tests. Are you referring to future functionality?
> 
> I think it would be good to keep some very basic validations in the default e2e if at all possible.

Sounds good
