### ISSUE TITLE
Unknown field errors when querying pre-v19 height cosmos transactions

### ISSUE THREAD

**Issue by GMaiolo** [zeta-chain/node#2835]
**Describe the Bug**
When querying `/cosmos/tx/v1beta1/txs?events=tx.height=4667204&page=1&limit=100&pagination.count_total=true`
With heights previous to the v19 update, nodes fail errors like the following

```
{
  "code": 2,
  "message": "codespace sdk code 2: tx parse error: errUnknownField \"*types.MsgVoteGasPrice\": {TagNum: 5, WireType:\"bytes\"}",
  "details": []
}
```

**To Reproduce**
Query a pre-v19 block like `/cosmos/tx/v1beta1/txs?events=tx.height=4667204&page=1&limit=100&pagination.count_total=true`

**Expected Behavior**
Transactions data should be returned successfully

**Comment by GMaiolo** [comment]
Another example
`/cosmos/tx/v1beta1/txs?events=tx.height=4687821&page=1&limit=1&pagination.count_total=true`

Result
```
{
  "code": 2,
  "message": "codespace sdk code 2: tx parse error: unable to resolve type URL /zetachain.zetacore.crosschain.MsgVoteOnObservedInboundTx",
  "details": []
}
```

**Comment by kingpinXD** [comment]
Both the example contain proto buffers which have been modified 

- VoteGasPrice  . The supply field with ID 5 was removed 
- MsgVoteOnObservedInboundTx was renamed to VoteInbound

**Comment by GMaiolo** [comment]
@kingpinXD would this impact someone that tries to create an indexer for ZetaChain from genesis?

**Comment by kingpinXD** [comment]
v21 modifies the `UpdateChainInfo` message , and is a breaking change 
We should verify on athens 3 , that we do not run into a similar issues as this 
https://github.com/zeta-chain/node/pull/2890

**Comment by GMaiolo** [comment]
@lumtis does this need an update on the nodes?
