### ISSUE TITLE
Integrate inscription-based inbounds generation in E2E suite and add deposit and call E2E test using inscription

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2900]
**Describe the Issue**
Follow-up of https://github.com/zeta-chain/node/pull/2727

- Replace the sidecar with a Go client to generate inscription
- Add a depositAndCall Bitcoin test using inscription and long message

Depends on https://github.com/zeta-chain/node/pull/2750

**Comment by Felipe-Rafael-Rosa** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive
