### ISSUE TITLE
Add new field in CCTX object to contains cross-chain call error

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#2913]
**Describe the Issue**

Currently the error of a cross-chain call is contained in the `cctx.status.status_message` which might contain other concatenated strings which makes the error difficult to read.

This issue is about adding a field to contains specifically the cross-chain call error.

In addition: adding a query to directly fetch this error message from the cctx index.

**Comment by kingpinXD** [comment]
We might have more than 1 error message, 
For example if a tx revertes and the abort fails , there would be two error messages , 
- original TX failure 
- revert tx failure 

I think it would be a good idea to make it clear to the user which is which 

For example this is a sample message 
```
“status_message”: “contract call failed: method ‘depositAndCall’, contract ‘0xEdf1c3275d13489aCdC6cD6eD246E72458B8795B’, args: [{[116 98 49 112 110 107 103 108 103 109 109 97 113 117 106 52 103 109 103 104 120 53 109 114 121 114 107 103 112 108 108 107 108 118 51 99 122 99 110 103 117 115 109 103 56 54 51 113 108 116 57 51 122 57 57 113 56 54 99 48 97 113] 0x0000000000000000000000000000000000000000 18332} 0x65a45c57636f9BcCeD4fe193A602008578BcA90b 493040 0x6E3c746E96411Def74c1bE5c858936A4a70C94cb [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 31 8 114 173 89 103 28 32 216 199 223 23 218 144 178 97 227 198 29 206 71 31 177 222 58 199 57 100 26 67 128 175 0 0 0 0 0 0 0 0 0 0 0 0 192 0 115 233 216 126 65 212 43 185 100 26 64 10 65 30 3 72 95 42 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 9 24 78 114 160 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 65 136 97 62 37 49 114 206 41 45 82 32 147 6 9 38 197 172 160 219 81 46 24 223 24 221 194 104 158 110 128 63 65 19 129 56 194 201 36 95 200 200 61 31 177 181 63 51 126 154 62 57 165 52 81 153 226 224 153 1 12 205 47 145 63 28 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]: execution reverted: ret 0x019cf77a: evm transaction execution failed : Outbound succeeded, revert executed” 
```

**Comment by kingpinXD** [comment]
Sample call 

`contract call failed: method 'depositAndCall', contract '0xEdf1c3275d13489aCdC6cD6eD246E72458B8795B', args: [{[116 98 49 112 57 50 54 117 121 121 102 121 48 57 57 101 114 112 121 115 118 103 122 56 99 120 48 120 113 99 107 119 114 120 119 122 50 55 55 100 109 118 119 113 48 115 102 113 102 120 115 57 115 108 112 113 54 53 56 103 103 51] 0x0000000000000000000000000000000000000000 18332} 0x65a45c57636f9BcCeD4fe193A602008578BcA90b 9294 0xE869b85987D86d8fBb8913f97A705B4741edE86E [232 105 184 89 135 216 109 143 187 137 19 249 122 112 91 71 65 237 232 110 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 64 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 31 8 114 173 89 103 28 32 216 199 223 23 218 144 178 97 227 198 29 206 71 31 177 222 58 199 57 100 26 67 128 175 0 0 0 0 0 0 0 0 0 0 0 0 126 135 72 161 246 45 197 182 19 229 130 54 52 51 181 206 92 51 225 55 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 128 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 65 175 191 243 152 14 157 230 78 250 153 214 115 97 4 131 21 152 237 112 234 246 43 190 249 73 184 226 162 133 70 151 205 109 70 59 128 91 14 111 31 146 175 64 231 41 105 163 226 174 101 216 41 59 122 188 107 40 167 241 147 210 184 116 198 28 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]: execution reverted: ret 0x: evm transaction execution failed : outTxGasFee(11800) more than available gas for tx (9294) | Identifiers : tb1p926uyyfy099erpysvgz8cx0xqckwrxwz277dmvwq0sfqfxs9slpq658gg3-18332-18332-0 : not enough gas`

**Comment by fbac** [comment]
> We might have more than 1 error message, For example if a tx revertes and the abort fails , there would be two error messages ,
> 
> * original TX failure
> * revert tx failure
> 
> I think it would be a good idea to make it clear to the user which is which
> 
> I feel it would be benificial for users to see something like
> 
> Outbound Error : XXX Revert Error : XXX

This can be done having multiple error/status fields, such as `cctx.outbound_status` and `cctx.revert_status`.
The problem is in that case we might want to include as well abort_status, etc...
