### ISSUE TITLE
Create RFC for Zetaclient V2

### ISSUE THREAD

**Issue by swift1337** [zeta-chain/node#2977]
**Describe the Issue**
We need a unified, simple, fault-tolerant, and efficient chain orchestration logic in zetaclientd for chain observation. Let’s design one and elaborate on this in the RFC docs.

**Expected Outcome**
An RFC with components, diagrams, interfaces, and an explanation of the new zetaclient orchestration.

**Comment by lumtis** [comment]
I remove https://github.com/zeta-chain/node/issues/1611 from the milestone and add this one.

Completing this document will give a clearer and more descriptive path toward a well structured ZetaClient codebase

**Comment by swift1337** [comment]
Related comment: https://github.com/zeta-chain/node/pull/3139#discussion_r1837982983
