### ISSUE TITLE
-core-home flag should be absolute path, not relative 

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#303]
`zetaclientd -core-home .zetacored` should use an absolute path and not be relative to the user's home directory. Using a relative path is confusing and prevent operators from customizing their node configurations. 

If  `-core-home` is not provided, then default to $HOME/.zetacored. If  `-core-home` is provided, use the absolute path provided. 

For example, if I want to run zetacored out of a a different directory such as  ` /srv/my_nodes/zeta` 
`zetaclientd -core-home /my_nodes/zeta/.zetacored` will fail. Because it tries to find `$HOME /my_nodes/zeta/.zetacored`

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
