### ISSUE TITLE
`eth_subscribe` `newHeads` not returning data

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#3093]
Trying new heads again, and it's returning the subscription, but not data.

```
websocat wss://zetachain-evm.blockpi.network/v1/ws/1295216a144e08ce8f0d0d452d16fe73cf1ee71e   
{ "jsonrpc": "2.0", "id": 1, "method": "eth_subscribe", "params": ["newHeads"] }
{"id":1,"jsonrpc":"2.0","result":"0xdf4b24d9cee37d3f3392ee8d02cea61c"}
```

```
wscat -c ~ wscat -c wss://zetachain-evm.blockpi.network/v1/ws/1295216a144e08ce8f0d0d452d16fe73cf1ee71e
Connected (press CTRL+C to quit)
> { "jsonrpc": "2.0", "id": 1, "method": "eth_subscribe", "params": ["newHeads"] }
< {"id":1,"jsonrpc":"2.0","result":"0xde3ef01eab89ab2d87809a396287ee30"}
>
```

From BlockPi:

> It is a bug from the new node client. Our test shows that v20.0.2  returns data but v20.0.5 does not.

**Comment by fadeev** [comment]
Is this related to https://github.com/zeta-chain/node/issues/3050 ?

**Comment by lumtis** [comment]
cc @skosito

**Comment by fadeev** [comment]
Odd, it's working now.

<img width="913" alt="Screenshot 2024-11-05 at 16 35 10" src="https://github.com/user-attachments/assets/c1dcdb70-5e30-4954-8948-95680dd36adb">
