### ISSUE TITLE
Build v21 image is failing

### ISSUE THREAD

**Issue by nebojsa-ristovic** [zeta-chain/node#3094]
**Describe the Bug**
docker build for node is failing for v21

**To Reproduce**
git clone this repo
cd to repo
git checkout release/v21
docker build --platform linux/x86_64/v8 . -f Dockerfile 
(it's same without platform - same error)

**Expected Behavior**
Image with version v21 to be built

**Screenshots**
```
> [builder 8/8] RUN expected_major_version=$(grep 'const releaseVersion = ' app/setup_handlers.go | awk -F'"' '{print $2}') &&     make install VERSION="${expected_major_version}" &&     git_hash=$(git rev-parse --short HEAD) &&     echo -n "${expected_major_version}-${git_hash}" > /go/delivery/zeta-node/expected_major_version:
#16 0.181 fatal: not a git repository (or any of the parent directories): .git
#16 0.182 fatal: not a git repository (or any of the parent directories): .git
```

**Environment (please complete the following information):**
- MacOS
- Sonoma 14.5

**Comment by gartnera** [comment]
Remove `.git` from the `.gitignore` file as a temporary workaround

**Comment by nebojsa-ristovic** [comment]
Thanks @gartnera, this worked actually. 
Removing from .dockerignore, not .gitignore, but I understood you.
