### ISSUE TITLE
Drop support for HSM

### ISSUE THREAD

**Issue by swift1337** [zeta-chain/node#3111]
Hardware Security Module is not used in the codebase. Let's simplify the code by removing it.
https://github.com/zeta-chain/node/blob/b516a46959a730bb1dd04dd6a8c0b8b6e05714c4/cmd/zetaclientd/hsm.go#L16

**Comment by gartnera** [comment]
I don't think "not used in the codebase" is necessarily accurate, it is definitely could be used for signing in zetaclient.

But regardless I asked the observer signers yesterday in slack if anyone was using this and I didn't get any responses. So I think it's safe to remove.

**Comment by kingpinXD** [comment]
The HSM signing logic was specifically requested to be added to zetaclient before the mainnet launch. 
It would be a good idea to confirm the reason behind the original request before removing it. 

I think the original request was from devops team ? Not sure, 
tagging @CharlieMc0 to get more clarity

**Comment by CharlieMc0** [comment]
Removing it is fine. No one used the functionality and the implementation is probably riskier because of the unmaintained dependency. We wanted to use HSM but it ended up not working well in practice
