### ISSUE TITLE
Fix precompiles E2E tests when running test-tss-migration

### ISSUE THREAD

**Issue by swift1337** [zeta-chain/node#3201]
I [disabled](https://github.com/zeta-chain/node/pull/3170/files#diff-b88b0296341624c3b4d6654372722db1df504e9213dea0fddecd313a1542aa54R190) precompiles tests from TSS migration e2e because they were failing:

```shell
Error: 1mprecompiles  | [ERROR]
Error Trace:	/go/delivery/zeta-node/e2e/e2etests/test_precompiles_bank_through_contract.go:150
	            		/go/delivery/zeta-node/e2e/e2etests/test_precompiles_distribute.go:58
Error:      	Not equal: 
	           expected: 0x0
	           actual  : 0x3e8
Messages:   	Balance should be 0, got: 1000
```

Let's modify the test to enable it to be run twice during the TSS migration process and then reenable it (by removing `--skip-precompiles`)

**Comment by gartnera** [comment]
Yeah I/we should probably add some CI that verifies you can run the e2e suite twice
