### ISSUE TITLE
"panic: UPGRADE "v23" NEEDED at height: 6087450" during upgrading to v23 with our own built zetacored binary

### ISSUE THREAD

**Issue by windycrypto** [zeta-chain/node#3264]
Our case is that we have forked the `zeta-chain/node` codebase and made some customizations on the APIs, during the decent v23 upgrade, we have merged the tag v23.0.0 of the upstream `zeta-chain/node` repo, and have built our own `zetacored` binary.

However, when we run the binary against the datadir, we get the error shown in the title.

With the zeta team's help, we've learnt that in v23 codebase it introduced a new mechanism to "tag" the version of the `zetacored` binary in the building stage.

https://github.com/zeta-chain/node/blob/release/v23/version.sh/#L1-L29
https://github.com/zeta-chain/node/blob/release/v23/app/setup_handlers.go/#L15-L30

So according to the version.sh we need either build from a tagged commit or do NODE_VERSION=23.0.0 make install to explicitly set the version.

We then updated our building script to prepended a `NODE_VERSION=23.0.0` to make install, then no more panic at all

**Comment by gartnera** [comment]
Thanks for filing this issue to help anyone else who hits this issue.

I also suggest running a testnet node to detect issues like this faster in the future.
