### ISSUE TITLE
Cosmos SDK HTTP API returns error when querying for a transaction hash

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#3280]
**Describe the Bug**

https://zetachain.blockpi.network/lcd/v1/public/cosmos/tx/v1beta1/txs/6C86B759289ACB1BE2EEC35619B7F9227EC4AF4AC235BC70F366C1DCDF76539A

```
{"code":2, "message":"codespace sdk code 2: tx parse error: errUnknownField \"*types.MsgAddOutboundTracker\": {TagNum: 7, WireType:\"varint\"}", "details":[]}
```

Same with other RPC providers.

Interestingly enough, this tx exists in ZetaScan's indexer:

https://explorer.zetachain.com/cosmos/tx/6C86B759289ACB1BE2EEC35619B7F9227EC4AF4AC235BC70F366C1DCDF76539A

**Comment by lumtis** [comment]
It shows up in other explorer as well https://zetachain.explorers.guru/transaction/6C86B759289ACB1BE2EEC35619B7F9227EC4AF4AC235BC70F366C1DCDF76539A

I think we already reached out to blockpi about this

**Comment by CharlieMc0** [comment]
Just because it exists in an explorer doesn't mean this isn't an active bug in v23. It could have been indexed using v22 and retrieving the same TX does not work after v23.

**Comment by swift1337** [comment]
It's related to this PR (https://github.com/zeta-chain/node/pull/3125); particularly [this](https://github.com/zeta-chain/node/pull/3125/files#diff-3ce3ebd3b798b60e643a0b36761f56f90cd1725ea9127b5372cf9119516cea78R97) change in protos. `reserved` is places validly, but seems there's an issue with decoding such messages
