### ISSUE TITLE
DRAFT: Arch: store TSS signed outbound tx in zetacore

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#351]
# Abstract

This proposes that zetacore prepares outbound tx, zetaclients TSS signs it, and the signed
tx is reported back and verified by zetacore. 

Furthermore, the tx recepit (together with merkle proofs) should be stored and verified by zetacore
as well. 

# Motivation

Currently, the outbound process is handled by zetaclients in a distributed manner, without
the knowledge of zetacore (consensus). This has a couple of undesirable implications: 

* The only way to reliably and securely synchronize between zetaclients is through zetacore; however the signed
outbound tx is not stored in zetacore state machine
* As a result, zetaclient may lose track of the tx hash as zetaclient does not have consensus and strong
resistance to failures. 
* Excessive amount of re-sign of the same tx is needed to ensure progress because zetacore does not
know whether an outbound tx is signed or not. 

# Spec

# Compatibility

# Security Consideration

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
