### ISSUE TITLE
ZetaClientd Uses unencrypted Validator Key 

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#360]
Zetaclientd is using an unencrypted validator key to sign transactions. This key should be encrypted or stored on a remote system.  Forcing operators to use an encrypted key is a big security issue and brand damage. 

From https://docs.cosmos.network/v0.46/run-node/keyring.html#the-test-backend

```
Test Backend
Provided for testing purposes only. The test backend is not recommended for use in production environments.
```

Related to #359

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
