### ISSUE TITLE
bug: missing observation on external chains

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#375]
https://mumbai.polygonscan.com/tx/0xa1cf450d91a3c2a3571fabcab2680f235704628988a1828db8b77f2c6c0bf33b

This tx is not observed. No trace of it in the logs. 

Possible solution: 
1. improve the robustness error handling
2. add admin "errata" tx to remind zetaclients some tx is missing.

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
