### ISSUE TITLE
Fork Ethermint JSON-RPC server and make it include non-Ethereum tx that calls EVM

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#433]
Currently Ethereum txs (initiated & signed by an EOA: e.g. metamask tx on zEVM) are processed by the Ethermint module and the ethermint RPC infrastructure indexes and provides Ethereum JSON-RPC [Ethermint ETH JSON-RPC](https://docs.evmos.org/developers/json-rpc/endpoints.html). 

However when cosmos txs call EVM (examples: 
https://github.com/zeta-chain/zeta-node/blob/f4b71ecc0bba901ce26f5274647b91fe14a28593/x/crosschain/keeper/keeper_cross_chain_tx_vote_inbound_tx.go#L69)

this transaction and receipt are not provided by ETH JSON-RPC, because this is not Ethereum tx and it's not included in the following important ETH JSON-RPC: 

- [eth_getBlockByNumber](https://docs.evmos.org/developers/json-rpc/server.html#eth-getblockbynumber)
- [eth_getBlockByHash](https://docs.evmos.org/developers/json-rpc/server.html#eth-getblockbyhash)
- [eth_getTransactionByHash](https://docs.evmos.org/developers/json-rpc/server.html#eth-gettransactionbyhash)
- [eth_getTransactionByBlockHashAndIndex](https://docs.evmos.org/developers/json-rpc/server.html#eth-gettransactionbyblockhashandindex)
- [eth_getTransactionReceipt](https://docs.evmos.org/developers/json-rpc/server.html#eth-gettransactionreceipt)
- [eth_getLogs](https://docs.evmos.org/developers/json-rpc/server.html#eth-getlogs)
- [eth_getFilterLogs](https://docs.evmos.org/developers/json-rpc/server.html#eth-getfilterlogs)

**Desired**: Synthesize Ethereum transaction/receipt/logs from the cosmos tx/responses/log (the EVM logs at least) and include them in the above RPC call results. 

Key References: 
 #420: forking ethermint RPC into zeta-node in which we implement the above additioins. This PR works on Ethermint 0.19 but (copy and redirect the ethermint/server and ethermint/rpc packages). Need to adapt to ethermint 0.21 as the current develop branch uses 0.21. 
#363 : this PR synthesizes and exposes cosmos tx as ethereum tx, but in a separate set of non standard RPC. Need to incorporate these into standard ETH JSON-RPC.

**Comment by lumtis** [comment]
Closing as it looks no longer relevant.

**Comment by lumtis** [comment]
Closing as it looks no longer relevant.
