### ISSUE TITLE
zetaclient persistent state management

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#449]
Each zetaclient has its own persistent state with leveldb; examples include

* last scanned block on external chains : https://github.com/zeta-chain/zeta-node/blob/1b5a1feca45be76cd70c23530716f3e2f7c7fad4/zetaclient/evm_client.go#L862
* observed external txs and receipts: 
https://github.com/zeta-chain/zeta-node/blob/1b5a1feca45be76cd70c23530716f3e2f7c7fad4/zetaclient/evm_client.go#L875
* bitcoin clients stores UTXOs and "used" UTXO (signed & broadcasted, but not yet mined) in leveldb as well. 

The persistent state management is a bit ad-hoc and while leveldb is simple & efficient, it does not have
proper database features such as filter by multiple keys etc. 

Also, there might be more states that need to be persisted, such as the signed outbound transaction. 

action items: 
- [x] explore using sqlite to replace leveldb as zetaclient persistent state
- [x] explore using some kind of ORM such as GORM to make persistence in sqlite easier and maybe persist more app state.

**Comment by lumtis** [comment]
Closed by #504
