### ISSUE TITLE
Audit Docker Enhancement

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#465]
ENHANCEMENT 1: .dockerignore FILE CAN BE OPTIMIZED FOR FASTER AND SMALLER BUILDS
Docker is used in the repository for creating test images. The folder .git/ is 7.3M in size making it the largest folder in the repository by far. By adding the entries .git/, .github/, and .gitignore to the .dockerignore file, it will be possible to speed up operation time when using Docker for testing.

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
