### ISSUE TITLE
Audit ISSUES evm grpc 

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#466]
ISSUE 8: INTEGER OVERFLOW BREAKS gRPC COMMUNICATION FOR LARGE BLOCK HEIGHTS
The file x/crosschain/keeper/grpc_zevm.go contains an endpoint that allows for querying information about a block using its height. An unsigned integer is converted to a signed integer in two locations here, resulting in an overflow.
Typically, when a value for height is higher than the current block height, an error is thrown. However, when an overflow occurs, the code does not return an error and instead returns information about the latest block.
This could result in usability issues:
Other software that interacts with the node should correctly assume that they will get an error message on illegal block heights. They will for blockHeight < x <= MAX_INT64 but outside of this range they will get unexpected behaviour
All queries will break for very large block heights as it will be impossible to query any blocks with a height > MAX_INT64. The latest block will always be returne.

**Comment by CharlieMc0** [comment]
SOLVED: The ZetaChain team solved the issue by implementing necessity
checks.
Commit IDs :
•a5aa77681ced5ea20cacdcfb6bbd5bdb385bdd2c
•37de781c228c08fa79ef3c1ce45da9d8a685e2a7
