### ISSUE TITLE
revert of omnichain smart contract should also  revert the inbound CCTX for refunding the fungible tokens

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#475]
Currently if an external transaction triggers omnichain smart contract which fails, that's the end of story and the sender of the external transaction will lose whatever was sent to TSS address/ERC20Custody contract. The inbound CCTX is directly put into `Aborted` state. 

We should put the inbound CCTX into `PendingRevert` state and add logic to zetaclient to implement this revert command that refunds user's fungible tokens on external chains.

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
