### ISSUE TITLE
Rename OutboundMined status to OutboundConfirmed

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#480]
# Change OutboundMined status to OutboundConfirmed
Not all connected chains use mining and I think `OutboundConfirmed` sends a clearer message than Mined. 

## Risks
There are dependencies and references to `OutboundMined` in the indexer, whitepaper, labs, and potentially other partner driven solutions. 

If we're going to make this change it would be best to do it before the Athens3 launch.

**Comment by lumtis** [comment]
I think mined has become over the time a universal term in crypto for a tx to be confirmed. I would consider that is fine to keep `OutboundMined `

**Comment by lumtis** [comment]
Per message above, please feel free to reopen if you disagree
