### ISSUE TITLE
ZetaCore state machine records and verifies TSS Keygen

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#493]
When the keygen ceremony finishes, the TSS Signers should together `keysign` a message and have each TSS keygen participants submit the message & signature to the state machine. 

The state machine should record the TSS pubkey & recover the signed message and verify the signature. 

This procedure accomplishes three things: 

1. The ZetaCore state machine now has a record of the TSS address (and pubkey)
2. The ZetaCore state machine knows that the TSS signers can successful keysign
3. Lays foundation for TSS key migration.

**Comment by lumtis** [comment]
I think we now have this information, feel free to reopen if still relevant
