### ISSUE TITLE
RPC Methods Are Broken, Slow, or Crash the RPC Nodes - BlockPi Report

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#506]
These RPC methods either don't work or can cause the node to lock up and/or crash when used. 

Reported by BlockPi 

method | problem | suggestion
-- | -- | --
/cosmos/params/v1beta1/params | invalid request, seems to be an old method already abandoned | delete this method
/ethermint/evm/v1/trace_tx | error "runtime error: invalid memory address or nil pointer dereference: panic", | not open to users, or fix
/zeta-chain/crosschain/cctx | response data too large, has parameter choice | not open to users, or only available with parameters
/zeta-chain/crosschain/cctxPending | response data too large, and has no parameter choice | not open to users, or add parameter choice
/zeta-chain/crosschain/keygen | not working, and description says there is an index parameter | to be fixed
/zeta-chain/crosschain/gasBalance/{index} | gasBalance has no content | will re-test when athena-3

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
