### ISSUE TITLE
ADD: Generic cosmos txs to perform privileged zEVM system contracts calls via policy group account

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#560]
There are a few privileged operations with regard to the system contracts on zEVM. 
For example, these of ZRC20:  and of system contract itself. 

Would need to have the policy account able to make those txs. These txs would need to be cosmos txs that calls these contracts as "FUNGIBLE MODULE" EOA. 

It would be tedious to create a separate cosmos txs for each privileged  contract functions. Much nicer to have a generic cosmos tx which could handle all of them. 

<img width="749" alt="image" src="https://user-images.githubusercontent.com/88689859/236971728-87f37870-4047-461b-a4a9-9698ba57fb5b.png">

<img width="627" alt="image" src="https://user-images.githubusercontent.com/88689859/236971758-a8ae896d-ed71-49db-bb3e-c5cc10aea45a.png">

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
