### ISSUE TITLE
Security Policy - Emergency Stop of inbound/outbound cctxs

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#601]
We need to the ability to stop inbound and outbound cctxs in case of emergency. This would be a temporary stop until additional investigation and action could take place. The pause would be for between 1 or 3 hours. If we determined a longer pause was necessary it could be completed using a different multi-sign policy. This policy action could be trigger by a single signer. 

As previously discussed and documented here - https://www.notion.so/zetachain/ZetaChain-Security-Groups-Signers-a1d817bf7abe4957881f1900a3404d7a

**Comment by lumtis** [comment]
We have this feature now AFAICT

**Comment by fadeev** [comment]
Closing as we already have this feature.
