### ISSUE TITLE
Security Policy - Manage Connector Contracts

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#602]
Ability to interact with connector contracts from the TSS address. Includes Pausing/Resume the contract and updated the TSS address. 

As previously discussed and documented here - https://www.notion.so/zetachain/ZetaChain-Security-Groups-Signers-a1d817bf7abe4957881f1900a3404d7a

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
