### ISSUE TITLE
base64 encoding of binary data instead of hex (base16)

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#63]
right now the hash/address are stored in hex string (effectively base16) which wastes storage of the state machine. 

For comparison, base16 uses 2 characters (2 Bytes) to encode a single byte, whereas base64 uses 4 bytes to encode 3bytes. 

Changing from hex to base64 improve storage efficiency from 50% to 75%, without major changes (bytes are still encoded in string so no type change needs to be done in protobuf). 

The most storage efficient encodes of course is the direct byte array ([]bytes in Go). However this requires major change to the protobuf definition.

**Comment by lumtis** [comment]
Looks no longer relevant, please feel free to reopen otherwise
