### ISSUE TITLE
Allow message passing revert transaction despite insufficient gas fee

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#645]
Someone could subsidize it.

Brandon:

>Need to narrow scope - lack-of-gas for message reverts.
> NFT use case - if reverts/aborts without ability to retry revert due to lack of gas, NFT is completely lost. Same potentially for fungible-token use cases with messaging

## Proposed solution

```[tasklist]
### Tasks
```

**Comment by lumtis** [comment]
We no longer use message passing
