### ISSUE TITLE
Remove or implement `SetNodeKeys` message

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#650]
`MsgSetNodeKeys` is registered, but it doesn't do anything unless I'm missing something. We might want to remove it or implement some functionality in this keeper method.

https://github.com/zeta-chain/zeta-node/blob/8838c02b3111b96ee658f84e1b820e3abfe76de5/x/crosschain/keeper/keeper_node_account.go#L101-L103

It's also registered twice:

https://github.com/zeta-chain/zeta-node/blob/8838c02b3111b96ee658f84e1b820e3abfe76de5/x/crosschain/types/cctx_utils.go#L21

https://github.com/zeta-chain/zeta-node/blob/8838c02b3111b96ee658f84e1b820e3abfe76de5/x/crosschain/types/cctx_utils.go#L24

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
