### ISSUE TITLE
Remove hard-coded policy addresses from `observer`'s default params

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#661]
As far as I understand these are set after the chain has been launched, so it's not necessary to have hard-coded values in the source.

https://github.com/zeta-chain/zeta-node/blob/3783141a9dc4b35b3dcc64f958bc56f3beff24d6/x/observer/types/params.go#L34-L53

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
