### ISSUE TITLE
upgrade path test

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#671]
Our versioning scheme is `vMAJOR.MINOR.PATCH`, with the understanding that
MAJOR bump means consensus-breaking change--upgrade module--need testing
MINOR bump means non consensus-breaking--but needs to be coordinated among OS validators--most likely zetaclient patches--do not need upgrade testing
PATCH bump is optional upgrade--non consensus breaking and non coordinated nor required--do not need upgrade path testing

The CI test should test only MAJOR version changes

the releaseVersion in the upgrade handler should only consists of a single number that is MAJOR

**Comment by lumtis** [comment]
Closing as it seems no longer relevant. Feel free to reopen. We should run local upgrade for all new releases.
