### ISSUE TITLE
fix: metamask defaults to AZETA instead of ZETA as the asset name 

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#715]
To reproduce, create a new network in Metamask, input any RPC from athens3 (here's an example: http://46.4.15.110:8545), input anything in the "Currency Symbol" will trigger a footnote saying RPC suggests AZETA. 

Somehow our Eth RPC seem to suggest AZETA because that's the only source of information metamask is able to get.

**Comment by fadeev** [comment]
Can we agree that we'll be using `tZETA` for testnet and `ZETA` for mainnet? If so, I'll update:

https://github.com/ethereum-lists/chains/edit/master/_data/chains/eip155-7001.json

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
