### ISSUE TITLE
Worklist for Stagenet launch

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#73]
Worklist for mainnet (stagenet) launch:

1. Reliable & fast signing
   a. parallel sign
   b. batch sign
2. Reliable & light observation
   a. Sequencer of discovery: light node 
   b. Report & handling of missed observation
   c. Incentives & punishment for spamming
3. Events instead of state:
   a. Send struct
   b. Archive mode: historic state to provide definitive source of truth
   b. Explorer: database and API
4. Abstract chain client for non-EVM compatible chain
   a. Query full node; scan blocks; register event/tx of interest
   b. Sign & Broadcast tx
   c. Query status of tx
5. Validator management:
   a. Join/leave
   b. Jail, slashing
   c. Incentives (the signing potentially need all signers!)
6. Error/exception handling:
   a. Waiting for catchup
   b. Error sending tx to ZetaChain or external chain
6. TSS Key:
   a. Keygen for new set of validators
   b. Re-share? Automatic 
7. Constraint & safety:
   a. Rate limit of funds transfered
   b. Supply check
   c. Ability to halt trade
8. Smart contracts:
   a. Integrate with uniswap v2 forks on connected chains
   b. Terraswap? 
9. DevOps
   a. logging
   b. monitoring, metric
   c. Alarms
   d. Launch all the processes; restart processes
10. Refactor
   a. Abstract external chainclient

**Comment by lumtis** [comment]
Closing as it looks no longer relevant.
