### ISSUE TITLE
Add consistency to query URLs

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#732]
Some URLs have `zetacore` in the path:

https://github.com/zeta-chain/zeta-node/blob/06c86d73021bb02b2353292ea128fca7abb91141/proto/observer/query.proto#L40

And some don't:

https://github.com/zeta-chain/zeta-node/blob/06c86d73021bb02b2353292ea128fca7abb91141/proto/observer/query.proto#L35

**Comment by lukema95** [comment]
It seems that this problem has been solved, you can close this issue

**Comment by lukema95** [comment]
> It seems that this problem has been solved, you can close this issue

Now the query.proto files of fungible and emissions still retain the path of zetacore, which should be removed. 

proto/fungible
https://github.com/zeta-chain/node/blob/32b135ac4d4276b3829854910fd5ca3fb792f5bd/proto/fungible/query.proto#L17

proto/emissions
https://github.com/zeta-chain/node/blob/32b135ac4d4276b3829854910fd5ca3fb792f5bd/proto/emissions/query.proto#L15C7-L15C7

**Comment by lumtis** [comment]
> > It seems that this problem has been solved, you can close this issue
> 
> Now the query.proto files of fungible and emissions still retain the path of zetacore, which should be removed.
> 
> proto/fungible
> 
> https://github.com/zeta-chain/node/blob/32b135ac4d4276b3829854910fd5ca3fb792f5bd/proto/fungible/query.proto#L17
> 
> proto/emissions https://github.com/zeta-chain/node/blob/32b135ac4d4276b3829854910fd5ca3fb792f5bd/proto/emissions/query.proto#L15C7-L15C7

Thanks for pointing this out @lukema95 👍 I may see that a PR has been created for this.
