### ISSUE TITLE
fix: event key with slash prevents swagger APIs such as /cosmos/tx/v1beta1/txs 

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#750]
It would be very useful to use the `/cosmos/tx/v1beta1/txs` and filter by event key attributes. 

One such use case is to search for the tx that "finalizes" a CCTX, queried by the CCTX index. 

Being able to do this via HTTP JSON-RPC service enables developing tooling as web app that has much larger reach than a CLI.

**Comment by kingpinXD** [comment]
This pr should close this issue 
https://github.com/zeta-chain/node/pull/803
