### ISSUE TITLE
Complete Full-Scope Audit that includes all relevant code

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#757]
Audits of Protocol code so far have been limited in scope and we must have all of the code used by the protocol audits. 

To date, only these directories have been considered in scope.
```
x/*
zetaclient/*
```

We must include 
```
app/*
cmd/*
common/*
proto/*
rpc/*
server/*
```

If we don't get this code audited we can't honestly promote that all of our code has been audited before we launched and it helps to have an extra set of eyes looking out for problems even if we consider the code low-risk.

**Comment by lumtis** [comment]
Closing as it seems no longer relevant with the current state of the project. Feel free to reopen it.
