### ISSUE TITLE
One bad RPC endpoint shouldn't disable zetaclient entirely

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#779]
If one RPC endpoint like BTC is unavailable then zetaclientd fails to start. 

One bad RPC endpoint shouldn't disable zetaclient entirely. Zetaclient should continue to process transactions on the other chains it had a functioning RPC endpoint for.

**Comment by brewmaster012** [comment]
@CharlieMc0 should we close this? I think at startup it's preferable to crash if RPC is not configured properly.
