### ISSUE TITLE
defensive: reserve invariant check 

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#798]
For all fungible assets that are sent to TSS, an internal ledger (ZRC20 contract) on zEVM track the ownership and balances. The following invariant must hold: 

reserve(balance of TSS address on external network) >= total_supply(tracking ZRC20)

They are not necessarily equal because there is donation option. 

Bugs, vulnerabilities, or improper handling of outbound gas fees might break this invariant. This invariant should be checked as frequently as possible and at appropriate sites.

**Comment by lumtis** [comment]
Closing as we now have the supply checker initialized in the ZetaClient, we can create further issues to make the supply checker functional
