### ISSUE TITLE
DRAFT: version number and its meaning

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#80]
x.y.z

- x: major version: major changes that requires network upgrades; e.g. AlphaNet -> BetaNet; PoA->PoS, etc. 

- y: minor version: state transition function changes; requires either an "upgrade" tx from all validators, or a network re-genesis. 

- z: patch level: uncoordinated upgrade; no consensus rule change; e.g. zetaclient change

**Comment by lumtis** [comment]
Looks no longer relevant, please feel free to reopen otherwise
