### ISSUE TITLE
Upgrade to v0.46.13

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#813]
Upgrade to https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.13

Fixes https://forum.cosmos.network/t/cosmos-sdk-security-advisory-barberry/10825

**Comment by lumtis** [comment]
What about upgrading to `v0.46.14` directly? https://github.com/cosmos/cosmos-sdk/releases/tag/v0.46.14

@brewmaster012 @kingpinXD @billyyang423
