### ISSUE TITLE
DRAFT: Events to reduce state bloat

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#82]
**Current situation:** The ZetaChain state machine keeps every Send (the representation of a meta-transaction that crosses chains) in its state with the Send state variable. The size of the state then grows linearly with the number of transaction. This bloats the state of ZetaChain. 

**Desired:** The state should keep track of "pending" transaction instead. It could also keep the recent history (30 days?) for quick reference to recent transactions. The old and "done" transactions should be archived. 

**Why?:** App state is more expensive than events stored in the Tendermint kv store (multi-store, cache, etc). Additionally, when network upgrades, the genesis file contains the whole state which can be large. 

**Solution:** Remove old and done Send and emit events. 

**Impact:** Old Send will not be in the state. The state machine can no longer serve as explorer. Need a separate ingestion and database to monitor and store the events and build indexes and analytics for query.

**Comment by lumtis** [comment]
Closing as it looks no longer relevant.
