### ISSUE TITLE
`zetacored keys` should default to the right HD path value

### ISSUE THREAD

**Issue by fadeev** [zeta-chain/node#856]
When recovering or creating new keys it's important to specify the HD path:

```
zetacored keys add --recover --hd-path "m/44'/60'/0'/0/0" bob
```

Ideally, a user shouldn't need to be explicit about this and the correct HD path should be set by default.

**Comment by lumtis** [comment]
I think we simply need to set a persistent flag.

Is it an issue that the HD path is never specified in the scripts? https://github.com/search?q=repo%3Azeta-chain%2Fnode+zetacored+keys&type=code
