### ISSUE TITLE
Move `ForeignCoinsList` from `fungible` to `observer` module

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#863]
https://github.com/zeta-chain/node/blob/1326c6e5fdf9893e6243db95221a9d14b28377ac/x/fungible/genesis.go#L33C1-L33C1

Would require a migrate script as the storage is modified

**Comment by kingpinXD** [comment]
@lumtis and @brewmaster012  , I don't think this is required anymore, but feel free to discuss if it is.
We can remove the comment based on this conversation

**Comment by lumtis** [comment]
> @lumtis and @brewmaster012 , I don't think this is required anymore, but feel free to discuss if it is. We can remove the comment based on this conversation

Yeah, I created the issue following the comment but it actually makes more sense to me to keep `foreignCoins` in `fungible` given the purpose of the module. Was there a specific reason for moving it?
