### ISSUE TITLE
Restore Prometheus Metrics for zetaclient and tss

### ISSUE THREAD

**Issue by CharlieMc0** [zeta-chain/node#895]
metrics used to be available at `9090:/metrics` for  zetaclient and tss in athens2 but it's no longer available in a3. This were very helpful to tracking the health of the network over time instead of just a single snapshot. This functionality should be revisited

**Comment by kevinssgh** [comment]
From my testing there are metrics at port 8886:/metrics.. Port might have been updated at some point.
