### ISSUE TITLE
`crosschain`: Use FindBallot in TSS voter 

### ISSUE THREAD

**Issue by kingpinXD** [zeta-chain/node#896]
Replace the following piece of code with the `FindBallot` function. 
`	ballot, found := k.zetaObserverKeeper.GetBallot(ctx, index)
	if !found {
		var voterList []string

		for _, nodeAccount := range k.zetaObserverKeeper.GetAllNodeAccount(ctx) {
			voterList = append(voterList, nodeAccount.Operator)
		}
		ballot = observerTypes.Ballot{
			Index:                "",
			BallotIdentifier:     index,
			VoterList:            voterList,
			Votes:                observerTypes.CreateVotes(len(voterList)),
			ObservationType:      observerTypes.ObservationType_TSSKeyGen,
			BallotThreshold:      sdk.MustNewDecFromStr("1.00"),
			BallotStatus:         observerTypes.BallotStatus_BallotInProgress,
			BallotCreationHeight: ctx.BlockHeight(),
		}
	}`

- `Find Ballot` would need to be modified to accept ballot thresholds 
- Threshold for different types of ballots needs to maintained in the params

**Comment by lumtis** [comment]
The observer list per chain is removed is it correct? Is the `ObserverMapper` structure still used?

Also I think this logic should be abstracted inside the `observer` keeper
```
for _, nodeAccount := range k.zetaObserverKeeper.GetAllNodeAccount(ctx) {
	voterList = append(voterList, nodeAccount.Operator)
}
```
```
voterList = k.zetaObserverKeeper.GetAllOperators()
```
I would also think we could have method `NewBallot` in `observer` keeper
```
func NewBallot(index string) Ballot {
  voterList = voterList = GetAllOperators()
  return Ballot{
		BallotIdentifier:     index,
		VoterList:            voterList,
		Votes:                observerTypes.CreateVotes(len(voterList)),
		ObservationType:      observerTypes.ObservationType_TSSKeyGen,
		BallotThreshold:      sdk.MustNewDecFromStr("1.00"),
		BallotStatus:        observerTypes.BallotStatus_BallotInProgress,
		BallotCreationHeight: ctx.BlockHeight(),
	}
}
```

> Threshold for different types of ballots needs to maintained in the params

In the current implementation, we read from `obsParams := k.GetParams(ctx).GetParamsForChain(chain)`, why changing it to `sdk.MustNewDecFromStr("1.00")`, do we also want to keep a unique one for all chains?

**Comment by fbac** [comment]
Closing this as won't fix, as the msg for vote TSS differs from the other messages, and does not carry ChainID, which makes it not possible to use FindBallot.
