### ISSUE TITLE
Replace `EmitEvent` with `EmitTypedEvent`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#910]
Using `EmitEvent` has been deprecated in favor of using `EmitTypedEvent`

It seems we use `EmitTypedEvent` in most places in the codebase, although it seems there are still some usages of `EmitEvent`:

https://github.com/zeta-chain/node/blob/487a54b61eaeec394d752315688f236b3b52bf7b/x/fungible/keeper/msg_server_deploy_fungible_coin_zrc20.go#L53

**Comment by tantodefi** [comment]
I'll take this one too :)

**Comment by lumtis** [comment]
Hey @tantodefi , we might have some client that breaks if we change the event format. I need to check to see if this is an issue or we can directly change to TypedEvent
