### ISSUE TITLE
`observer`: Revise policy type names

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#932]
Context: https://github.com/zeta-chain/node/pull/912#discussion_r1287334012

Make a walkthrough of the different policy types and rename them appropriately depending on their usage.

**Comment by lumtis** [comment]
Did a walkthrough of the types:

- `Policy_Type_stop_inbound_cctx`: can update permission flags to disable inbound and outbound in cctx.

**Should be renamed**

- `Policy_Type_deploy_fungible_coin` - can:
  - Whitelist ERC20
  - Deploy foreign coin
  - Remove foreign coin
  - Update system contract
  - Pause ZRC20
  - Update ZRC20 bytecode
  - Update withdraw fees

**Should be renamed**

- `Policy_Type_update_client_params` - update core params, looks up-to-date although `client_params` could be renamed into `core_params`

- `Policy_Type_update_keygen_block` - update TSS address and Keygen

**Should be renamed**

- `Policy_Type_out_tx_tracker` - Add to out tx tracker or remove from out tx tracker, looks up-to-date

- `Policy_Type_add_observer` - Add observer, looks up-to-date

We might also want to merge some of the rule to simplify the authorization structure.

cc @zeta-chain/protocol-engineering

**Comment by fadeev** [comment]
Create a doc with all the privileged message types. Depending on how complex this ends up being, we might consolidate the roles.

**Comment by lumtis** [comment]
Update: doc set up on Notion: Engineering/Protocol Docs/Observer Policy Types

**Comment by fadeev** [comment]
https://www.notion.so/zetachain/Observer-Policy-Types-4e501dd64dfc460180a361f9b8507310
