### ISSUE TITLE
Clean observer `BeginBlocker`

### ISSUE THREAD

**Issue by lumtis** [zeta-chain/node#962]
It seems that we have unnecessary logic in `BeginBlocker`
These values are set to a constant every block:
```
k.SetPermissionFlags(ctx, types.PermissionFlags{IsInboundEnabled: false})
k.SetKeygen(ctx, types.Keygen{BlockNumber: math.MaxInt64})
``` 

Although it is a single O(1) operation we try to have the minimum store write operation in begin blocker as these operations are executed every blocks

**Comment by kingpinXD** [comment]
The observer list might get affected from one of these hooks 
https://github.com/zeta-chain/zeta-node/blob/6d1dbcba28262c6afebc7ed38bdf0f8ca3d4cae2/x/observer/keeper/hooks.go#L14-L45

It is not the normal flow to remove an observer , but can happen

**Comment by lumtis** [comment]
Looks no longer relevant
