### ISSUE TITLE
bug: missing outbound tx confirmation

### ISSUE THREAD

**Issue by brewmaster012** [zeta-chain/node#989]
There are missing confirmation of outtx on a3. 
Here's a list on mumbai (currently 14)
http://46.4.15.110:1317/zeta-chain/crosschain/cctxPendingMissing?chainId=80001
And a list on bsctestnet (current 6)
http://46.4.15.110:1317/zeta-chain/crosschain/cctxPendingMissing?chainId=97

These CCTX outbound nonce are below NonceLow so will not appear in CctxPendingAll RPC call, therefore zetaclient will not try to re-try/keysigg or confirm it. 

Need to have zetaclients confirm these bogus  "Pending" Cctx reliably and cheaply.

**Comment by lumtis** [comment]
Closing as it looks no longer relevant.
